document.addEventListener("contextmenu", e => e.preventDefault());
document.addEventListener("selectstart", e => e.preventDefault());
document.addEventListener("dragstart", e => e.preventDefault());
/*UI LOGIC*/
function openTab(id) {

    document.querySelectorAll(".tab-content")
        .forEach(el => {
            el.style.display = "none";
            el.classList.remove("active");
        });

    document.querySelectorAll(".nav-btn")
        .forEach(btn => btn.classList.toggle("active", btn.dataset.tab === id));

    const tab = document.getElementById(id);

    tab.style.display = "block";
    tab.classList.add("active");

    if (id === "roles") {
        resetBotSystems();
    }

    window.scrollTo({
        top: tab.offsetTop - 70,
        behavior: "smooth"
    });

}
function setExpandableHeight(content, isOpen) {
    if (!content) {
        return;
    }

    content.style.maxHeight = isOpen ? `${content.scrollHeight}px` : "0px";
}
function isRoleSection(section) {
    return !!section?.closest("#bot-systems-roles");
}
function syncExpandablePanelsSoon() {
    window.requestAnimationFrame(() => {
        syncExpandablePanels();
    });
}
function syncExpandablePanels() {
    document.querySelectorAll(".weekday").forEach(section => {
        if (isRoleSection(section)) {
            return;
        }

        setExpandableHeight(section.querySelector(".day-events"), section.classList.contains("active"));
    });

    document.querySelectorAll(".event").forEach(card => {
        setExpandableHeight(card.querySelector(".description"), card.classList.contains("active"));
    });

    document.querySelectorAll(".game-doc-card").forEach(card => {
        setExpandableHeight(card.querySelector(".game-doc-description"), card.classList.contains("active"));
    });
}
const toggleDay = el => {
    const section = el.parentElement;
    const isOpen = !section.classList.contains("active");

    section.classList.toggle("active", isOpen);

    if (!isRoleSection(section)) {
        setExpandableHeight(section.querySelector(".day-events"), isOpen);
    }

    syncExpandablePanelsSoon();
};
const toggleEvent = el => {
    const isOpen = !el.classList.contains("active");

    el.classList.toggle("active", isOpen);
    setExpandableHeight(el.querySelector(".description"), isOpen);
    syncExpandablePanelsSoon();
};
const toggleRule = el => {
    el.classList.toggle("active");
};
function toggleRole(header) {
    const role = header.closest(".role");

    if (!role) {
        return;
    }

    const isActive = role.classList.contains("active");

    document.querySelectorAll(".role.active").forEach(card => {
        card.classList.remove("active");
    });

    if (!isActive) {
        role.classList.add("active");
    }
}
function getGameCards() {
    return document.querySelectorAll("#games-content .game-doc-card");
}
function getGamesFocusState() {
    return {
        gamesContent: document.getElementById("games-content"),
        focusBar: document.querySelector("[data-games-focus-bar]"),
        focusTitle: document.querySelector("[data-current-game-label]")
    };
}
function scrollGameTarget(target) {
    if (!target) {
        return;
    }

    const top = target.getBoundingClientRect().top + window.scrollY - 92;

    window.scrollTo({
        top,
        behavior: "smooth"
    });
}
function showOnlyGame(gameId) {
    const allGames = getGameCards();
    const target = document.getElementById(`game-${gameId}`);
    const { gamesContent, focusBar, focusTitle } = getGamesFocusState();

    allGames.forEach(el => {
        el.style.display = "block";
        el.classList.remove("active");
        setExpandableHeight(el.querySelector(".game-doc-description"), false);
    });

    if (!target) {
        showAllGames();
        return false;
    }

    target.style.display = "block";
    target.classList.add("active");
    setExpandableHeight(target.querySelector(".game-doc-description"), true);

    if (gamesContent) {
        gamesContent.classList.remove("is-focused");
    }

    if (focusBar) {
        focusBar.hidden = true;
    }

    if (focusTitle) {
        const gameTitle = target.querySelector(".role-header, .game-doc-header")?.textContent?.trim() || "Гра";
        focusTitle.textContent = `🕹 ${gameTitle}`;
    }

    scrollGameTarget(focusBar && !focusBar.hidden ? focusBar : target);
    return true;
}
function showAllGames(shouldScroll = false) {
    const { gamesContent, focusBar, focusTitle } = getGamesFocusState();

    getGameCards().forEach(el => {
        el.style.display = "block";
        el.classList.remove("active");
        setExpandableHeight(el.querySelector(".game-doc-description"), false);
    });

    if (gamesContent) {
        gamesContent.classList.remove("is-focused");
    }

    if (focusBar) {
        focusBar.hidden = true;
    }

    if (focusTitle) {
        focusTitle.textContent = "";
    }

    if (shouldScroll && gamesContent) {
        scrollGameTarget(gamesContent);
    }
}
function setupGameFocusMode() {
    document.querySelectorAll("#games-content .game-doc-card[data-game]").forEach(card => {
        if (card.dataset.focusReady === "true") {
            return;
        }

        card.addEventListener("click", () => {
            showOnlyGame(card.dataset.game);
        });

        card.dataset.focusReady = "true";
    });

    document.querySelectorAll("[data-show-all-games]").forEach(button => {
        if (button.dataset.focusReady === "true") {
            return;
        }

        button.addEventListener("click", () => {
            showAllGames(true);
        });

        button.dataset.focusReady = "true";
    });
}

/*анті-школьнік-угон*/
document.addEventListener("keydown", e => {
    if (
        e.key === "F12" ||
        (e.ctrlKey && e.shiftKey && ["I", "J", "C"].includes(e.key)) ||
        (e.ctrlKey && e.key === "U")
    ) {
        e.preventDefault();
        alert("DevTools заблоковано.");
    }
});
/*Base64 decoder*/
const b64 = s => {
    try {
        return new TextDecoder().decode(
            Uint8Array.from(atob(s), c => c.charCodeAt(0))
        );
    } catch (e) {
        console.warn("Base64 decode error:", e);
        return "";
    }
};
/*EVENTS (13 штук)*/
const encodedEvents = [
    "8J+MktCjINGB0LLRltGC0ZYg8J2TlPCdk7fwnZOq8J2TtvCdk7jwnZO78J2TqvCdk63wnZO4IPCdk63wnZOuIPCdk77wnZO3IPCdk7zwnZO+8J2TrsOx8J2TuCDRiNC40YDRj9GC0YzRgdGPINGC0YDQuNCy0L7QttC90ZYg0YfRg9GC0LrQuOKApg0KDQrQmtCw0LbRg9GC0YwsINGJ0L4g0LLQvdC+0YfRliDQt8q80Y/QstC70Y/RlNGC0YzRgdGPINGC0ZbQvdGMINCx0LXQtyDQtNC+0LzRgyDwn5Wv77iPDQoNCtCR0LXQtyDRltC80LXQvdGWLiDQkdC10Lcg0L/RgNCw0LLQuNC7Lg0KDQrQm9C40YjQtSDQutGA0L7QutC4INCyINGC0LXQvNGA0Y/QstGWINGC0LAg0LLQuNCx0ZbRgCwg0Y/QutC40Lkg0L3QtSDQv9GA0L7QsdCw0YfQsNGUIPCfmLXigI3wn5KrDQoNCg0KDQrQndCw0LLRltGC0Ywg0JzQsNGE0ZbRjyDRh9Cw0YLRgyDQvdCw0YHRgtC+0YDQvtC20ZYg8J+YsQ0KDQrQkdC+INC90ZbRhdGC0L4g0L3QtSDQt9C90LDRlCwg0LfQsCDQutC40Lwg0LLRltC9INC/0YDQuNC50LTQtSDRhtGW0ZTRlyDQvdC+0YfRluKApg0KDQoNCg0K8J+Vr++4jyDQodGD0YLRjCDQs9GA0Lg6DQoNCuKAvO+4jyDQoyDQn9CV0KDQqNCjINCd0IbQpyDQo9Ch0IYg0JDQmtCi0JjQktCd0IYg0KDQntCb0IYg0KHQmtCG0J/QkNCu0KLQrCDQpdCe0JTQmCwg0LAg0JLQntCb0J7QptCu0JPQkCDQn9CY0KjQlSDQkiDQn9CfINCS0JXQlNCj0KfQhtCZ4oC877iPDQoNCvCfjJEg0JrQvtC20L3RgyDQvdGW0Ycg0LLQvtC70L7RhtGO0LPQsCDQvtCx0LjRgNCw0ZQsINC60YPQtNC4INC/0ZbRgtC4LA0KDQrRliDRgtC+0LksINC00L4g0LrQvtCz0L4g0LLRltC9INC/0YDQuNC50LTQtSDigJQg0LfQvdC40LrQsNGUINC3INCz0YDQuCDwn5KADQoNCvCfqbgg0JrQntCW0JXQnSwg0YMg0LrQvtCz0L4g0LHRg9CyINCy0L7Qu9C+0YbRjtCz0LAg0LLQvdC+0YfRliwg0JvQhtCS0JDQhA0KDQoo0LrQvtC80LDQvdC00LAg8J+RiSAvbGVhdmUpDQoNCg0KDQrimqDvuI8g0JPRgNCwINCf0KDQntCU0J7QktCW0KPQhNCi0KzQodCvINCx0LXQtyDRgdC60LDRgdGD0LLQsNC90L3Rjy4NCg0K0J3QsNCy0ZbRgtGMINGP0LrRidC+INCy0L7Qu9C+0YbRjtCz0YMg0L/QvtCy0ZbRgdGP0YLRjCDQsNCx0L4g0LLQscq80Y7RgtGMLCDRltCy0LXQvdGCINGW0LTQtSDQtNCw0LvRliDQtNC+INGE0ZbQvdCw0LvRgyDwn4yYDQoNCg0KDQrwn6m40KXRgtC+INC30LTQvtCx0YPQtNC1INC/0LXRgNC10LzQvtCz0YM/DQoNCvCfj4bQk9GA0LDQstC10YbRjCwg0Y/QutC40Lkg0J/QldCg0KjQmNCcINC/0L7QstGW0YHQuNGC0YwgLyDQstCxyrzRlCDQstC+0LvQvtGG0Y7Qs9GDDQoNCvCfj4bQktC+0LvQvtGG0Y7Qs9CwLCDRj9C60YnQviDQtNGW0LnQtNC1INC00L4g0LrRltC90YbRjyDRliDQudC+0LPQviDQvdC1INCy0LjQutGA0LjRjtGC0YwNCg0KDQoNCvCflKsg0JTQntCX0JLQntCb0K/QhNCi0KzQodCvOg0KDQrinJTvuI8g0YHQu9GW0LTRh9C+0LzRgyDRgdGC0YDRltC70Y/RgtC4INCx0LXQtyDRh9C10LrRgyDQtyDQlNCg0KPQk9Ce0Icg0L3QvtGH0ZYNCg0K4pyU77iPINGA0LDQvdC00L7QvCDwn46yDQoNCg0KDQrimpnvuI8g0JPRgNCwOg0KDQrinZfvuI8g0JHQtdC3INC30LzRltC9DQoNCuKdl++4jyDQkdC10Lcg0LHQsNGE0ZbQsg0KDQrinZfvuI8g0KPQstGW0LzQutC90LXQvdGWINCy0YHRliDQvNC+0LbQu9C40LLRliDRgNC+0LvRlg==",
    "8J+MkSDQoyDRgdGC0LDRgNC40YUg0LrQstCw0YDRgtCw0LvQsNGFINC80ZbRgdGC0LAg0ZQg0YHQstGW0YLQu9C+LCDRj9C60LUg0L3QtSDQs9GA0ZbRlC4NCg0K0JLQvtC90L4g0L3QtSDRgNGP0YLRg9GULiDQndC1INC/0L7Qv9C10YDQtdC00LbQsNGULg0KDQrwn4yYINCS0L7QvdC+INC70LjRiNC1INC+0LHQuNGA0LDRlC4NCg0K0JrQvtC70Lgg0L3RltGHINC+0L/Rg9GB0LrQsNGU0YLRjNGB0Y8g0L3QsCDQtNCw0YXQuCDwn4yZLCDRgyDRgtC10LzRgNGP0LLRliDRgdC/0LDQu9Cw0YXRg9GUINC70ZbRhdGC0LDRgC4NCg0K0JnQvtCz0L4g0L/QvtC70YPQvOKAmdGPINC/0L7QstGW0LvRjNC90LXigKYg0LPRg9GB0YLQteKApiDQvdC10LLRltC00LLQvtGA0L7RgtC90LUuIPCflKUNCg0K0J3RltGF0YLQviDQvdC1INC30L3QsNGULCDQvdCwINC60L7Qs9C+INCy0L/QsNC00LUg0YHQstGW0YLQu9C+Lg0KDQrQkNC70LUg0Y/QutGJ0L4g0LLQvtC90L4g0YLQvtGA0LrQvdGD0LvQvtGB0Y8g0YLQtdCx0LUg4oCUDQoNCtGC0Lgg0LLQttC1INGB0YLQvtGX0Ygg0LzRltC2INC00LLQvtGFINGB0LLRltGC0LDQvdC60ZbQsi4NCg0K0JHQviDRhtC10Lkg0LvRltGF0YLQsNGAINC90LUg0L/RgNC+0YHRgtC+INGB0LLRltGC0LjRgtGMLg0KDQrQktGW0L0g0LLRltC00YDQsNGF0L7QstGD0ZQuDQoNCg0KDQrwn5Wv77iPINCh0YPRgtGMINCz0YDQuDoNCg0K8J+MmSDQndCG0KcNCg0K0J/RltGB0LvRjyDQv9C+0YfQsNGC0LrRgyDQs9GA0Lg6DQoNCtCS0LXQtNGD0YfQsCDRgNCw0L3QtNC+0LzQvdC+ICjRh9C10YDQtdC3INGA0LDQvdC00L7QvNCw0LnQt9C10YApINC+0LHQuNGA0LDRlCAxINCz0YDQsNCy0YbRjw0KDQrQn9C40YjQtSDQudC+0LzRgyDQsiDQn9CfOg0KDQrwn5SlINCd0LAg0YLQtdCx0LUg0LLQv9Cw0LIg0JrRgNC40LLQsNCy0LjQuSDQm9GW0YXRgtCw0YANCg0K0IYg0L/Rg9Cx0LvRltGH0L3QviDQsiDRh9Cw0YIg0L/QuNGI0LU6DQoNCvCfjJgg0JvRltGF0YLQsNGAINC+0YHQstGW0YLQuNCyINC60L7Qs9C+0YHRjCDRhtGW0ZTRlyDQvdC+0YfRluKApg0KDQoNCg0K4piA77iPINCU0JXQndCsDQoNCtCT0YDQsNCy0YbRliDQvdC1INC30L3QsNGO0YLRjCDRhdGC0L4g4oCc0L7RgdCy0ZbRgtC70LXQvdC40LnigJ0uDQoNCtCv0LrRidC+INCy0LTQtdC90Ywg0LnQvtCz0L4g0L/QvtCy0ZbRgdGP0YLRjCDigJQNCg0K0LLRltC9INC/0YDQvtGB0YLQviDQstC40LHRg9Cy0LDRlCDRgdGC0LDQvdC00LDRgNGC0L3Qvi4NCg0K4pqg77iPINCv0LrRidC+INC50L7Qs9C+INCd0JUg0L/QvtCy0ZbRgdC40LvQuCDigJQNCg0K0L/RltGB0LvRjyDQvdGW0YfQvdC+0LPQviDQv9GW0LTRgdGD0LzQutGDINCy0LXQtNGD0YfQsCDQv9C40YjQtToNCg0K8J+UpSDQm9GW0YXRgtCw0YAg0LfQsNCx0YDQsNCyINGB0LLQvtGOINC20LXRgNGC0LLRgw0KDQrRliDQs9GA0LDQstC10YbRjCDRgNC+0LHQuNGC0YwgL2xlYXZlDQoNCg0KDQrwn5SrINCU0J7Ql9CS0J7Qm9Cv0ITQotCs0KHQrzoNCg0K4pyU77iPINGB0YLQsNC90LTQsNGA0YLQvdGWINC00ZbRlyDRgNC+0LvQtdC5DQoNCuKclO+4jyDQutC70LDRgdC40YfQvdC40Lkg0YTQvtGA0LzQsNGCINCz0YDQuA0KDQrinJTvuI8g0LHRg9C00Ywt0Y/QutGWINGB0YLRgNCw0YLQtdCz0ZbRlyDRgtCwINCx0LvQtdGEDQoNCuKclO+4jyDQoNCw0L3QtNC+0LwgDQoNCg0KDQrimpnvuI8g0JPRgNCwOg0KDQrinZfvuI8g0JHQtdC3INCx0LDRhNGW0LINCg0K4p2X77iPINCj0YHRliDRgNC+0LvRliDRg9Cy0ZbQvNC60L3QtdC90ZYNCg0K4p2X77iPIOKAnNCe0YHQstGW0YLQu9C10L3QvdGP4oCdINC00ZbRlCDRj9C6INC/0YDQuNGF0L7QstCw0L3QuNC5INGC0LDQudC80LXRgCDRgdC80LXRgNGC0ZYgDQoNCg0KDQrQotCwINC/0L7QutC4INC80ZbRgdGC0L4g0YjRg9C60LDRlCDQstC40L3QvdC40YUg4oCUDQoNCtCb0ZbRhdGC0LDRgCDRg9C20LUg0LfRgNC+0LHQuNCyINGB0LLRltC5INCy0LjQsdGW0YAuDQoNCtCGINC60L7Qu9C4INGB0L/QsNC70LDRhdGD0ZQg0L/QvtC70YPQvOKAmdGPIPCflKUNCg0K0YXRgtC+0YHRjCDRgNC+0LfRg9C80ZbRlOKApg0KDQrRidC+INGH0LDRgdGDINCx0ZbQu9GM0YjQtSDQvdC1INC30LDQu9C40YjQuNC70L7RgdGMLiDwn4yY",
    "8J+MkiDQoyDRgdCy0ZbRgtGWIPCdk5TwnZO38J2TqvCdk7bwnZO48J2Tu/Cdk6rwnZOt8J2TuCDwnZOt8J2TriDwnZO+8J2TtyDwnZO88J2TvvCdk67DsfCdk7gg0LfigJnRj9Cy0LvRj9GU0YLRjNGB0Y8g0L3QvtCy0LAg0LPRgNCwINC00L7Qu9GW4oCmDQoNCtCa0LDQttGD0YLRjCwg0LrQvtC20LXQvSDRltC3INC90LDRgSDRltC00LUg0LLRg9C70LjRhtGP0LzQuCDQvdC1INGB0LDQvC4NCg0K0JHQviDQt9CwINGB0L/QuNC90L7RjiDigJQg0LfQsNCy0LbQtNC4INGB0YLQvtGX0YLRjCDRhdGC0L7RgdGMLg0KDQrQotC40YXQuNC5LiDQndC10LLQuNC00LjQvNC40LkuDQoNCtCi0L7QuSwg0YXRgtC+INGH0LXQutCw0ZQg0YLQstC+0LPQviDRgNGW0YjQtdC90L3RjyDwn5Wv77iPDQoNCtCm0YzQvtCz0L4g0YDQsNC30YMg0LLQvtGA0L7QsyDQvdC1INCy0LjQv9Cw0LTQutC+0LLQuNC5Lg0KDQrQktGW0L0g0L7QsdGA0LDQvdC40Lkg0LTQu9GPINGC0LXQsdC1Lg0KDQrQhiDQu9C40YjQtSDRgtC4INC80L7QttC10Ygg0LLQuNGA0ZbRiNC40YLQuCDigJQNCg0K0YfQuCDRgdGC0LDQvdC1INCy0ZbQvSDRgtCy0L7RlNGOINC/0LXRgNC10LzQvtCz0L7RjuKApg0KDQrRh9C4INGC0LLQvtGX0Lwg0L/RgNC+0LrQu9GP0YLRgtGP0Lwg8J+WpA0KDQrQndCw0LLRltGC0Ywg0JzQsNGE0ZbRjyDQvdC10YDQstGD0ZQg8J+YiA0KDQrQkdC+INGC0LXQv9C10YAg0YMg0LrQvtC20L3QvtCz0L4g0ZQg0L7RgdC+0LHQuNGB0YLQsCDRhtGW0LvRjC4NCg0K0J7RgdC+0LHQuNGB0YLQuNC5INGA0LDRhdGD0L3QvtC6Lg0KDQrQntGB0L7QsdC40YHRgtCwINGC0ZbQvdGMLg0KDQoNCg0K8J+Vr++4jyDQodGD0YLRjCDQs9GA0Lg6DQoNCvCfjq0g0J/QtdGA0LXQtCDRgdGC0LDRgNGC0L7QvCDQutC+0LbQtdC9INCz0YDQsNCy0LXRhtGMINC+0YLRgNC40LzRg9GUINCyINCf0J8gwqvRgtCw0ZTQvNC90L7Qs9C+INCy0L7RgNC+0LPQsMK7Lg0KDQoo0JvQuNGI0LUg0YLQuCDQt9C90LDRlNGILCDRhdGC0L4g0YbQtS4pDQoNCg0KDQrimIDvuI8g0K/QutGJ0L4g0L/RltC0INGH0LDRgSDQs9C+0LvQvtGB0YPQstCw0L3QvdGPINGC0Lgg0L/QvtCy0ZbRgdC40Ygg0YHQsNC80LUg0YHQstC+0LPQviDQstC+0YDQvtCz0LAg4oCUDQoNCtGC0Lgg0L7RgtGA0LjQvNGD0ZTRiCDQv9C10YDQtdC80L7Qs9GDLg0KDQrinZfvuI8g0JLQvtGA0L7QsyDRgyDQutC+0LbQvdC+0LPQviDRgdCy0ZbQuS4NCg0K4p2X77iPINCd0ZbRhdGC0L4g0L3QtSDQt9C90LDRlCwg0YXRgtC+INC30LAg0LrQuNC8INC/0L7Qu9GO0ZQuDQoNCg0KDQrwn6m4INCp0L4g0YbQtSDQt9C80ZbQvdGO0ZQ/DQoNCtCi0LXQv9C10YAg0LPRgNCwINC90LUg0LvQuNGI0LUg0LrQvtC80LDQvdC00L3QsC4NCg0K0KLQtdC/0LXRgCDQutC+0LbQtdC9INC80LDRlCDQstC70LDRgdC90YMg0LzRltGB0ZbRji4NCg0K0KLQuCDQvNC+0LbQtdGIOg0KDQrwn5SlINC00L7Qv9C+0LzQsNCz0LDRgtC4INC60L7QvNCw0L3QtNGWDQoNCvCflKUg0LPRgNCw0YLQuCDQvdCwINC+0YHQvtCx0LjRgdGC0YMg0LLQuNCz0L7QtNGDDQoNCvCflKUg0L/RltC00YHRgtCw0LLQu9GP0YLQuCDRltC90YjQuNGFLCDRidC+0LEg0LTRltGB0YLQsNGC0LjRgdGPINC00L4g0YHQstC+0ZTRlyDRhtGW0LvRlg0KDQoNCg0K0JDQu9C1INC/0LDQvOKAmdGP0YLQsNC54oCmDQoNCtC80L7QttC70LjQstC+LCDRhdGC0L7RgdGMINGC0LDQuiDRgdCw0LzQviDQv9C+0LvRjtGUINC90LAg0YLQtdCx0LUg8J+WpA0KDQoNCg0K8J+MkSDQpdGC0L4g0L3QsNCy0LDQttC40YLRjNGB0Y8g0LLQsdC40YLQuCDRgdCy0L7RjiDRgtGW0L3RjD8NCg0K0KXRgtC+INC30YDQvtC30YPQvNGW0ZQsINGJ0L4g0LfQsCDQvdC40Lwg0YHQsNC80LjQvCDRg9C20LUg0YHRgtC10LbQsNGC0Yw/DQoNCtCR0L4g0YbRjNC+0LPQviDRgNCw0LfRgyDQvdC10LHQtdC30L/QtdC60LAg0L3QtSDQv9C+0L/QtdGA0LXQtNGD4oCmDQoNCtCy0L7QvdCwINGB0YLQvtGX0YLRjCDQv9GA0L7RgdGC0L4g0LfQsCDRgdC/0LjQvdC+0Y4g8J+Vr++4j/CflqQ=",
    "0KMg0YbRltC5INCz0YDRliDQvdGW0YfQvtCz0L4g0L3QtSDQv9GA0LjRhdC+0LLQsNC90L4sINC90ZbRh9C+0LPQviDQvdC1INC30LDRhdC40YnQtdC90L4uDQoNCtCi0YPRgiDQvdC10LzQsNGUINC80LDQs9GW0Zcg4pyoLCDQsdC+0L3Rg9GB0ZbQsiDwn5KOINGH0Lgg0YnQuNGC0ZbQsiDwn5uh77iPLg0KDQrQhCDRgtGW0LvRjNC60Lgg0YLQuCwg0YLQstC+0Zcg0YDRltGI0LXQvdC90Y8g8J+Xoe+4jyDRliDRhdC+0LvQvtC00L3QsCDQu9C+0LPRltC60LAg8J+noC4NCg0K0JLQuCDQv9GA0L7QutC40LTQsNGU0YLQtdGB0Y8g0LIg0YHQstGW0YLRliwg0LTQtSDQv9C+0LzQuNC70LrQsCDQutCw0YDQsNGU0YLRjNGB0Y8g0LLRltC00YDQsNC30YMg4pqhLA0KDQrQsCDQutC+0LbQtdC9INC60YDQvtC6INC80L7QttC1INGB0YLQsNGC0Lgg0L7RgdGC0LDQvdC90ZbQvCDwn5KALg0KDQoNCg0KIOKZpe+4jyDQntGB0L7QsdC70LjQstC+0YHRgtGWINGA0LXQttC40LzRgw0KDQog4p2MINCW0L7QtNC90LjRhSDQsdCw0YTRltCyLCDQttC+0LTQvdC40YUg0LHQvtC90YPRgdGW0LINCg0KIPCflbXvuI/igI3imYLvuI8g0JLRgdGWINGA0L7Qu9GWINCw0LrRgtC40LLQvdGWDQoNCiDij7Mg0JrQvtC20LXQvSDRhdGW0LQg4oCUINC/0LjRgtCw0L3QvdGPINCy0LjQttC40LLQsNC90L3Rjw0KDQog8J+kliDQkdC+0YIg0L/QvtC60LDQt9GD0ZQg0YbRltC70ZYg0LDQutGC0LjQstC90LjRhSDRgNC+0LvQtdC5DQoNCg0KDQog8J+noCDQn9GA0LDQstC40LvQsA0KDQrQpNC+0YDQvNCw0YIg0LrQu9Cw0YHQuNGH0L3QvtGXINCc0LDRhNGW0ZcgLCDQsNC70LUg0LHQtdC3INC/0L7RgdC70LDQsdC70LXQvdGMOg0KDQoNCg0KIPCfjJ4g0JTQtdC90Ywg4oCUINC+0LHQs9C+0LLQvtGA0LXQvdC90Y8gINGWINCz0L7Qu9C+0YHRg9Cy0LDQvdC90Y8gDQoNCiDwn4yMINCd0ZbRhyDigJQg0LLRltC00LrRgNC40YLQsCDQs9GA0LAgLCDQtNC1INGC0YDQtdCx0LAg0LTRltGP0YLQuCDQvtCx0LXRgNC10LbQvdC+DQoNCg0KDQog8J+SgCDQhNC00LjQvdCwINGD0LzQvtCy0LAg4oCUINCy0LjQttC40YLQuA0KDQrQoyDRhtGM0L7QvNGDINGB0LLRltGC0ZYg0YDQvtC70Ywg8J+OrSDQvdC1INGA0Y/RgtGD0ZQuDQoNCg0KDQrQoNGP0YLRg9GUINC70LjRiNC1Og0KDQog8J+ptyDRhdC+0LvQvtC00L3QsCDQs9C+0LvQvtCy0LAgDQoNCiDimqEg0YjQstC40LTQutCwINGA0LXQsNC60YbRltGPDQoNCiDwn5SuINCy0LzRltC90L3RjyDRh9C40YLQsNGC0Lgg0LvRjtC00LXQuQ0KDQoNCg0K0KLRltC70YzQutC4INGC0ZYsINGF0YLQviDQt9C80L7QttC1INC60L7QvdGC0YDQvtC70Y7QstCw0YLQuCDRhdCw0L7RgSDRliDQvdC1INC30YDQvtCx0LjRgtGMINC60YDQvtC60YMg0LIg0YLQtdC80YDRj9Cy0ZYg0L3QsNC+0YHQu9GW0L8sINC00L7QttC40LLRg9GC0Ywg0LTQviDQv9C10YDQtdC80L7Qs9C4IPCfj4YuDQoNCtCg0LXRiNGC0LAg4oCUINGB0YLQsNC90YPRgtGMINGH0LDRgdGC0LjQvdC+0Y4g0L3QvtGH0ZYg8J+MmA0KDQrQk9C+0YLQvtCy0ZYg0LLQuNC/0YDQvtCx0YPQstCw0YLQuCDRgdC10LHQtSDQsdC10Lcg0LbQvtC00L3QuNGFINC30LDRhdC40YHQvdC40YUg0YLRgNGO0LrRltCyIPCfp6g/DQoNCtCi0L7QtNGWINCz0YDQsCDQv9C+0YfQuNC90LDRlNGC0YzRgdGPIPCflKXwn5Wv77iP",
    "8J+MkSDQmtCw0LbRg9GC0YwsINGDINC60L7QttC90L7QvNGDINC80ZbRgdGC0ZYg0ZQg0YLQvtC5LCDRhdGC0L4g0L3QtSDQstCx0LjQstCw0ZQg0LrQu9C40L3QutC+0LzigKYNCg0K0JLRltC9INCy0LHQuNCy0LDRlCDQtNC+0YLQuNC60L7QvC4NCg0K8J+MmCDQmtC+0LvQuCDQvdGW0Ycg0L7Qv9GD0YHQutCw0ZTRgtGM0YHRjyDQvdCwINC80ZbRgdGC0L4g8J+MmSwg0YHQtdGA0LXQtCDQs9GA0LDQstGG0ZbQsiDQt+KAmdGP0LLQu9GP0ZTRgtGM0YHRjyDRgtGW0L3RjCDigJQg0YHQv9C+0LrRg9GB0LvQuNCy0LAsINGC0LjRhdCwLCDQvdC10LHQtdC30L/QtdGH0L3QsC4g0IfRlyDQv9C+0YbRltC70YPQvdC+0Log0L3QtSDQt9Cw0LvQuNGI0LDRlCDRgdC70ZbQtNGW0LLigKYg0LDQu9C1INC30LDQu9C40YjQsNGUINC80ZbRgtC60YMg8J+Siw0KDQrQndGW0YXRgtC+INC90LUg0LfQvdCw0ZQsINGF0YLQviDQstGW0L0uDQoNCtCd0ZbRhdGC0L4g0L3QtSDQsdCw0YfQuNGC0Ywg0LzQvtC80LXQvdGC0YMuDQoNCtCQ0LvQtSDQutC+0LvQuCDQvdCw0YLQvtCy0L8g0YDQvtCx0LjRgtGMINGB0LLRltC5INCy0LjQsdGW0YAg4oCUINC00L7Qu9GPINC00LLQvtGFINC/0LXRgNC10L/Qu9GW0YLQsNGU0YLRjNGB0Y8g0L3QsNC30LDQstC20LTQuC4NCg0K0JHQviDRltC90LrQvtC70Lgg0YHQvNC10YDRgtGMINC/0YDQuNGF0L7QtNC40YLRjCDQvdC1INC3INC/0L7RgdGC0YDRltC70L7QvOKApg0KDQrQsCDQtyDQv9C+0YbRltC70YPQvdC60L7QvC4g8J+Siw0KDQoNCg0K8J+Vr++4jyDQodGD0YLRjCDQs9GA0Lg6DQoNCvCfjq0g0J/QtdGA0LXQtCDQv9C+0YfQsNGC0LrQvtC8INCz0YDQuCDRgNCw0L3QtNC+0LzQvdC+INC+0LHQuNGA0LDRlNGC0YzRgdGPIOKAnNCh0L/QvtC60YPRgdC90LjQuuKAnS4NCg0K8J+MmSDQktC90L7Rh9GWINCh0L/QvtC60YPRgdC90LjQuiDQvtCx0LjRgNCw0ZQgMSDQs9GA0LDQstGG0Y8uDQoNCtCe0LHRgNCw0L3QuNC5INC+0YLRgNC40LzRg9GUINC80ZbRgtC60YMg8J+SiyAo0YLQsNGU0LzQvdC+KS4NCg0K4piA77iPINCv0LrRidC+INGG0YzQvtCz0L4g0LPRgNCw0LLRhtGPINC/0L7QstGW0YHRj9GC0YwgLQ0KDQrQodC/0L7QutGD0YHQvdC40Log0LDQstGC0L7QvNCw0YLQuNGH0L3QviDQs9C40L3QtSDRgtC10LYgKC9sZWF2ZSkuDQoNCg0KDQrwn5SrINCU0J7Ql9CS0J7Qm9Cv0ITQotCs0KHQrzoNCg0K4pyU77iPINGB0YLQsNC90LTQsNGA0YLQvdGWINC00ZbRlyDRgNC+0LvQtdC5DQoNCuKclO+4jyDQutC70LDRgdC40YfQvdC40Lkg0YTQvtGA0LzQsNGCINCz0YDQuA0KDQrinJTvuI8g0LDQutGC0LjQstC90LAg0YHRgtGA0LDRgtC10LPRltGPINGC0LAg0LHQu9C10YQNCg0KDQoNCuKame+4jyDQk9GA0LA6DQoNCuKdl++4jyDQkdC10Lcg0LfQvNGW0L0g0LzQtdGF0LDQvdGW0LrQuA0KDQrinZfvuI8g0JHQtdC3INC00L7QtNCw0YLQutC+0LLQuNGFINCx0LDRhNGW0LINCg0K4p2X77iPINCj0YHRliDRgNC+0LvRliDRg9Cy0ZbQvNC60L3QtdC90ZYNCg0K4p2X77iPINCc0ZbRgtC60LAg0LTRltGUINC70LjRiNC1INC00L4g0LzQvtC80LXQvdGC0YMg0YHRgtGA0LDRgtC4IA0KDQoNCg0K8J+MkSDQpdGC0L4g0YDQuNC30LjQutC90LUg0L/RgNC40LLigJnRj9C30LDRgtC4INGB0LLQvtGOINC00L7Qu9GOINC00L4g0ZbQvdGI0L7Qs9C+Pw0KDQrQpdGC0L4g0LfRltCz0YDQsNGUINGC0L7QvdC60L7igKYg0ZYg0LfQsNC70LjRiNC40YLRjNGB0Y8g0LIg0YLRltC90ZY/DQoNCvCfkosg0J/QvtGG0ZbQu9GD0L3QvtC6INGB0YLQsNCy0LjRgtGM0YHRjyDQu9C40YjQtSDRgNCw0Lcg0LfQsCDQvdGW0YcuDQoNCtCGINC80L7QttC1INGB0YLQsNGC0Lgg0L7RgdGC0LDQvdC90ZbQvCDQtNC70Y8g0LTQstC+0YXigKYNCg0K",
    "8J+MkSDQoyDRgtC10LzRgNGP0LLRliDQt9Cw0LLQttC00Lgg0ZQg0YLQvtC5LCDRhdGC0L4g0L3QtSDQs9C+0LLQvtGA0LjRgtGMINCy0LPQvtC70L7RgeKApg0KDQrQktGW0L0g0L3QtSDRgdC/0LXRgNC10YfQsNGU0YLRjNGB0Y8uINCd0LUg0L/QtdGA0LXQutC+0L3Rg9GULiDQndC1INCz0L7Qu9C+0YHRg9GUINCy0ZbQtNC60YDQuNGC0L4uDQoNCvCfjJgg0JLRltC9INC/0YDQvtGB0YLQviDRgdC80LjQutCw0ZQg0LfQsCDQvdC40YLQutC4LiDwn5W477iPDQoNCtCa0L7Qu9C4INC90ZbRhyDQvdCw0LrRgNC40LLQsNGUINC80ZbRgdGC0L4g8J+MmSwg0L7QtNC90LAg0LTRg9GI0LAg0YHRgtCw0ZQg0LzQsNGA0ZbQvtC90LXRgtC60L7Rji4NCg0K0JHQtdC3INC60YDQuNC60ZbQsi4NCg0K0JHQtdC3INCy0LjQsdC+0YDRgy4NCg0K0IYg0L3QsNGB0YLRg9C/0L3QvtCz0L4g0LTQvdGPINGF0YLQvtGB0Ywg0L/RgNC+0LPQvtC70L7RgdGD0ZTigKYNCg0K0LDQu9C1INGG0LUg0LHRg9C00LUg0L3QtSDQudC+0LPQviDRgNGW0YjQtdC90L3Rjy4g8J+OrQ0KDQrQkdC+INGW0L3QutC+0LvQuCDRgdC/0YDQsNCy0LbQvdGPINGB0LjQu9CwIOKAlCDQvdC1INCyINGB0LvQvtCy0LDRhS4NCg0K0JAg0LIg0LrQvtC90YLRgNC+0LvRli4NCg0KDQoNCvCfla/vuI8g0KHRg9GC0Ywg0LPRgNC4Og0KDQrwn46tINCf0LXRgNC10LQg0L/QvtGH0LDRgtC60L7QvCDQs9GA0Lgg0JLQtdC00YPRh9CwINCy0LjQv9Cw0LTQutC+0LLQuNC8INGH0LjQvdC+0Lwg0L7QsdC40YDQsNGUIDEg0LPRgNCw0LLRhtGPIOKAlCDQm9GP0LvRjNC60L7QstC+0LQuDQoNCtCZ0L7Qs9C+INGA0L7Qu9GMINCd0JUg0LfQvNGW0L3RjtGU0YLRjNGB0Y8gKNCy0ZbQvSDQt9Cw0LvQuNGI0LDRlNGC0YzRgdGPINC80LjRgNC90LjQvCDQsNCx0L4g0LzQsNGE0ZbRlNGOKS4NCg0KDQoNCvCfjJkg0J3QhtCnDQoNCtCb0Y/Qu9GM0LrQvtCy0L7QtCDQv9C40YjQtSDQstC10LTRg9GH0ZbQuToNCg0K0JrQvtCz0L4g0LHQtdGA0YMg0L/RltC0INC60L7QvdGC0YDQvtC70YwNCg0K0JLQtdC00YPRh9CwINC/0LjRiNC1INC+0LHRgNCw0L3QvtC80YMg0LIg0J/QnzoNCg0K8J+OrSDQotC4INC/0ZbQtCDQutC+0L3RgtGA0L7Qu9C10LwuINCX0LDQstGC0YDQsCDQs9C+0LvQvtGB0YPRlNGIINC30LAgKNC90ZbQuikNCg0KDQoNCuKYgO+4jyDQlNCV0J3QrA0KDQrQk9GA0LDQstC10YbRjCDQt9C+0LHQvtCyyrzRj9C30LDQvdC40Lkg0L/RgNC+0LPQvtC70L7RgdGD0LLQsNGC0Lgg0YLQsNC6LCDRj9C6INGB0LrQsNC30LDQvdC+Lg0KDQrinYwg0K/QutGJ0L4g0L3RliDigJQgL2xlYXZlDQoNCg0KDQrwn5SrINCU0J7Ql9CS0J7Qm9Cv0ITQotCs0KHQrzoNCg0K4pyU77iPINCg0LDQvdC00L7QvCANCg0K4pyU77iPINGB0YLRgNCw0YLQtdCz0ZbRh9C90LUg0LLQuNC60L7RgNC40YHRgtCw0L3QvdGPINC60L7QvdGC0YDQvtC70Y4NCg0KDQoNCuKame+4jyDQk9GA0LA6DQoNCuKdl++4jyDQkdC10Lcg0LHQsNGE0ZbQsg0KDQrinZfvuI8g0JrQvtC90YLRgNC+0LvRjCDQtNGW0ZQg0LvQuNGI0LUg0L3QsCDQvtC00LjQvSDQtNC10L3RjA0KDQoNCg0K8J+MkSDQpdGC0L4g0YHRgtCw0L3QtSDQvNCw0YDRltC+0L3QtdGC0LrQvtGOPw0KDQrQpdGC0L4g0L3QtdC/0L7QvNGW0YLQvdC+INC/0LXRgNC10L/QuNGI0LUg0YDQtdC30YPQu9GM0YLQsNGCINCz0L7Qu9C+0YHRg9Cy0LDQvdC90Y8/DQoNCvCfjJgg0JAg0LrQvtC70Lgg0LLRgdC1INC30LDQstC10YDRiNC40YLRjNGB0Y8g4oCUINGF0YLQvtGB0Ywg0LfQsNC70LjRiNC40YLRjNGB0Y8g0Lcg0LLRltC00YfRg9GC0YLRj9C8LCDRidC+INGG0LUg0LHRg9CyINC90LUg0LnQvtCz0L4g0LLQuNCx0ZbRgOKApg0KDQrQsNC70LUg0LHRg9C00LUg0LLQttC1INC/0ZbQt9C90L4u",
    "8J+MkSDQoyDRgtC10LzRgNGP0LLRliDQutC+0LbQtdC9INGJ0L7RgdGMINC/0ZbQtNC+0LfRgNGO0ZQuDQoNCtCQ0LvQtSDQvdC1INC60L7QttC10L0g0LPQvtGC0L7QstC40Lkg0YHQutCw0LfQsNGC0Lgg0YbQtSDQstCz0L7Qu9C+0YEuDQoNCvCfjJgg0KbRltGU0Zcg0L3QvtGH0ZYg0LzRltGB0YLQviDQv9C10YDQtdGC0LLQvtGA0Y7RlNGC0YzRgdGPINC90LAg0LrRltC80L3QsNGC0YMg0LHQtdC3INGB0LLRltC00LrRltCyLg0KDQrQotC4INC80L7QttC10Ygg0L/RgNC+0YjQtdC/0L7RgtGW0YLQuCDQv9GA0LDQstC00YMuDQoNCtCQINC80L7QttC10YggLSDQutC40L3Rg9GC0Lgg0YLRltC90Ywg0L3QsCDQvdC10LLQuNC90L3QvtCz0L4uDQoNCtCd0ZbRhdGC0L4g0L3QtSDQtNGW0LfQvdCw0ZTRgtGM0YHRjywg0YXRgtC+INGG0LUg0L3QsNC/0LjRgdCw0LIuDQoNCtCi0LAg0LrQvtC70Lgg0LLRltC00LrRgNC40ZTRgtGM0YHRjyDRgNC+0LvRjCAtDQoNCtGH0LjRj9GB0Ywg0LfQsNC/0LjRgdC60LAg0YHRgtCw0L3QtSDQstC40YDQvtC60L7QvC4NCg0K0JHQviDRltC90LrQvtC70Lgg0LTQvtGB0YLQsNGC0L3RjNC+INC+0LTQvdC+0LPQviDQtNC+0L3QvtGB0YPigKYNCg0K0YnQvtCxINC/0LXRgNC10L/QuNGB0LDRgtC4INGF0ZbQtCDQs9GA0LguDQoNCg0KDQrwn5Wv77iPINCh0YPRgtGMINCz0YDQuDoNCg0K0KHRgtCw0L3QtNCw0YDRgtC90LAg0LPRgNCwDQoNCtCg0L7Qu9GWINCx0LXQtyDQt9C80ZbQvQ0KDQoNCg0K8J+MmSDQndCG0KcgKNC/0LXRgNGI0LApDQoNCtCjINC/0LXRgNGI0YMg0L3RltGHINC60L7QttC10L0g0YPRh9Cw0YHQvdC40Log0L/QuNGI0LUg0LLQtdC00YPRh9C+0LzRgyDQsiDQn9CfIOKAnNC00L7QvdC+0YHigJ0g0L3QsCDQvtC00L3QvtCz0L4g0LPRgNCw0LLRhtGPLg0KDQrQpNC+0YDQvNCw0YIg0L/RgNC40LrQu9Cw0LTRgzoNCg0K0JTQvtC90L7RgSDQvdCwIEDRjtC3IC0g0LLRltC9INC80LDRhNGW0Y8NCg0K0JrQvtC20LXQvSDQvNCw0ZQg0L/RgNCw0LLQviDQt9GA0L7QsdC40YLQuCDQu9C40YjQtSDQvtC00LjQvSDQtNC+0L3QvtGBLg0KDQoNCg0K4piA77iPINCU0JXQndCsDQoNCtCU0LXQvdGMINC/0YDQvtGF0L7QtNC40YLRjCDRgdGC0LDQvdC00LDRgNGC0L3Qvi4NCg0K0JrQvtC70Lgg0LHRg9C00Ywt0Y/QutC40Lkg0LPRgNCw0LLQtdGG0Ywg0L/QvtC80LjRgNCw0ZQgKNC/0L7QstGW0YHQuNC70Lgg0LDQsdC+INCy0LHQuNC70LgpIC0NCg0K0LLQtdC00YPRh9C40Lkg0LfQstGW0YDRj9GUINCy0YHRliDQtNC+0L3QvtGB0Lgg0L3QsCDRhtGOINC70Y7QtNC40L3Rgy4NCg0K4pyFINCv0LrRidC+INGF0YLQvtGB0Ywg0YLQvtGH0L3QviDQstCz0LDQtNCw0LIg0LnQvtCz0L4g0YDQvtC70YwgLQ0KDQrRhtC10Lkg0LPRgNCw0LLQtdGG0Ywg0L7QtNGA0LDQt9GDINC+0YLRgNC40LzRg9GUINC+0LrRgNC10LzRgyDQv9C10YDQtdC80L7Qs9GDLg0KDQrinYwg0KLRliwg0YXRgtC+INC90LUg0LLQs9Cw0LTQsNCyIC0NCg0K0L7RgtGA0LjQvNGD0Y7RgtGMINGJ0LUg0L7QtNC40L0g0YjQsNC90YEg0LfRgNC+0LHQuNGC0Lgg0L3QvtCy0LjQuSDQtNC+0L3QvtGBINC90LAg0LHRg9C00Ywt0Y/QutC+0LPQviDQs9GA0LDQstGG0Y8uDQoNCg0KDQrwn5SrINCU0J7Ql9CS0J7Qm9Cv0ITQotCs0KHQrzoNCg0K4pyU77iPINGB0YLQsNC90LTQsNGA0YLQvdGWINC00ZbRlyDRgNC+0LvQtdC5DQoNCuKclO+4jyDQutC70LDRgdC40YfQvdC40Lkg0YTQvtGA0LzQsNGCINCz0YDQuA0KDQrinJTvuI8g0LHRg9C00Ywt0Y/QutCwINGB0YLRgNCw0YLQtdCz0ZbRjyDQsNCx0L4g0LHQu9C10YQNCg0KDQoNCuKame+4jyDQk9GA0LA6DQoNCuKdl++4jyDQkdC10Lcg0LfQvNGW0L0g0LzQtdGF0LDQvdGW0LrQuA0KDQrinZfvuI8g0JHQtdC3INC00L7QtNCw0YLQutC+0LLQuNGFINCx0LDRhNGW0LINCg0K4p2X77iPINCU0L7QvdC+0YEg0LfQsNCy0LbQtNC4INCw0L3QvtC90ZbQvNC90LjQuQ0KDQrinZfvuI8g0J/QtdGA0LXQvNC+0LPQsCDQvNC+0LbQu9C40LLQsCDQsiDQsdGD0LTRjC3Rj9C60LjQuSDQvNC+0LzQtdC90YIg0L/RltGB0LvRjyDQstGW0LTQutGA0LjRgtGC0Y8g0YDQvtC70ZYNCg0KDQoNCvCfjJIg0KXRgtC+INC/0L7RgdGC0LDQstC40YLRjCDQvdCwINGW0L3RgtGD0ZfRhtGW0Y4/DQoNCtCl0YLQviDRgNC40LfQuNC60L3QtSDQt9Cx0YDQtdGF0LDRgtC4Pw0KDQrwn6m2INCGINC60L7Qu9C4INCy0ZbQtNC60YDQuNGU0YLRjNGB0Y8g0YDQvtC70Ywg4oCUDQoNCtGF0YLQvtGB0Ywg0LzQvtCy0YfQutC4INGD0YHQvNGW0YXQvdC10YLRjNGB0Y8sDQoNCtCx0L4g0LnQvtCz0L4g0LTQvtC90L7RgSDQstC40Y/QstC40YLRjNGB0Y8g0L/RgNCw0LLQtNC+0Y4uDQoNCg==",
    "4o+wINCp0L7Rh9C10YLQstC10YDQs9CwIA0KDQrQk9GA0LAg0L/QvtGH0LjQvdCw0ZTRgtGM0YHRjyDRgtCw0LwsINC00LUg0LfQsNC60ZbQvdGH0YPRlNGC0YzRgdGPINC30LLQuNGH0L3QtS4NCg0K0JzRltGB0YLQviDRgdC/0LjRgtGMINC/0ZbQtCDRgtGW0L3QvdGOINGF0LDQvtGB0YMsINCwINC90ZbRhyDRgtC40YXQviDQv9GW0LTQutCw0LfRg9GUINC90L7QstGWINC/0YDQsNCy0LjQu9CwLg0KDQrQltC+0LTQvdCwINGA0L7Qu9GMINC90LUg0LfQsNC60YDRltC/0LvQtdC90LAuDQoNCtCi0Lgg0LzQvtC20LXRiCDQsdGD0YLQuCDQs9C10YDQvtGU0Lwg0LLRgNCw0L3RhtGWLCDQsCDQstC90L7Rh9GWINC/0YDQvtC60LjQvdGD0YLQuNGB0Y8g0ZbQvdGI0LjQvCDigJQg0ZYg0LvQuNGI0LUg0YLQtdC80YDRj9Cy0LAg0LfQvdCw0ZQsINC60L7Qs9C+INC+0LHRgNCw0YLQuCDQvdCw0YHRgtGD0L/QvdC40LwuDQoNCg0KDQog4pml77iPINCT0L7Qu9C+0LLQvdCwINC+0YHQvtCx0LvQuNCy0ZbRgdGC0YwNCg0KINCg0L7Qu9GWINC30LzRltC90Y7RjtGC0YzRgdGPINGJ0L7QvdC+0YfRlg0KDQog0JbQvtC00LXQvSDQs9GA0LDQstC10YbRjCDQvdC1INC30LDRgdGC0YDQsNGF0L7QstCw0L3QuNC5DQoNCiDQl9Cw0LHRg9C00YzRgtC1INC/0YDQviDQt9Cy0LjRh9C90ZYg0YHRgtGA0LDRgtC10LPRltGXDQoNCiDQkdC+0YIg0L/QvtC60LDQt9GD0ZQg0YbRltC70ZYg0LDQutGC0LjQstC90LjRhSDRgNC+0LvQtdC5DQoNCg0KDQog8J+noCDQn9GA0LDQstC40LvQsA0KDQrQpNC+0YDQvNCw0YIg0LrQu9Cw0YHQuNGH0L3QvtGXINCc0LDRhNGW0Zcg0Lcg0LvQtdCz0LrQvtGOINC80L7QtNC40YTRltC60LDRhtGW0ZTRjjoNCg0KDQoNCiDQlNC10L3RjCDigJQg0L7QsdCz0L7QstC+0YDQtdC90L3Rjywg0LDQvdCw0LvRltC3INGWINCz0L7Qu9C+0YHRg9Cy0LDQvdC90Y8NCg0KINCd0ZbRhyDigJQg0LLRltC00LrRgNC40YLQsCDQs9GA0LAsINC00LUg0LrQvtC20LXQvSDQvNC+0LbQtSDQtNGW0Y/RgtC4INGB0LzRltC70LjQstC+INCw0LHQviDQvtCx0LXRgNC10LbQvdC+DQoNCiDwn5KAINCE0LTQuNC90LAg0YPQvNC+0LLQsCDigJQg0LLQuNC20LjRgtC4DQoNCg0KDQrQoyDRhtGW0Lkg0LPRgNGWINC90LUg0LLQsNC20LvQuNCy0LAg0YDQvtC70YwsINCwOg0KDQog8J+ptyDRhdC+0LvQvtC00L3QsCDQs9C+0LvQvtCy0LANCg0KIPCfqbcg0YjQstC40LTQutCwINCw0LTQsNC/0YLQsNGG0ZbRjw0KDQog8J+ptyDQstC80ZbQvdC90Y8g0YfQuNGC0LDRgtC4INC70Y7QtNC10LkNCg0KDQoNCtCi0ZbQu9GM0LrQuCDRgtGWLCDRhdGC0L4g0LfQvNC+0LbQtSDRgtGA0LjQvNCw0YLQuCDRgtC10LzQvyDRliDQvdC1INGA0L7Qt9Cz0YPQsdC40YLRjNGB0Y8sINC00L7QttC40LLRg9GC0Ywg0LTQviDQv9C10YDQtdC80L7Qs9C4Lg0KDQrQkCDRgNC10YjRgtCw4oCmINC30LvQsNC80LDRjtGC0YzRgdGPINCy0LbQtSDQv9GW0YHQu9GPINC/0LXRgNGI0L7RlyDQvdC+0YfRliDwn5iPDQoNCg0KDQrQk9C+0YLQvtCy0ZYg0L/QvtGA0LjQvdGD0YLQuCDRgyDRhdCw0L7RgSDRliDQstC40L/RgNC+0LHRg9Cy0LDRgtC4INCy0LvQsNGB0L3RgyDRltC90YLRg9GX0YbRltGOPw0KDQrQotC+0LTRliDQs9GA0LAg0L/QvtGH0LjQvdCw0ZTRgtGM0YHRjyDwn5Sl",
    "8J+MkSDQn9C10YDQtdC0INCz0YDQvtGOINCyINGC0ZbQvdGWINC80ZbRgdGP0YbRjywg0LTQvtC70YPQvdCw0Y7RgtGMINC30LLRg9C60LjigKYg8J+OtiDQt9Cy0YPQutC4INGP0LrRliDQvNC+0LbRg9GC0Ywg0LLQuNGA0ZbRiNC40YLQuCDQtNC+0LvRjiDimpbvuI8sINC/0YDQuNGB0LvRg9GF0LDQudGB0Y8sINGD0LLQsNC20L3QviDQv9GA0LjRgdC70YPRhdCw0LnRgdGPLCDQsNC00LbQtSDRhtC1INGC0LUg0YnQviDQvNC+0LbQtSDQstC/0LvQuNC90YPRgtC4INC90LAg0YLQstC+0ZQg0LzQsNC50LHRg9GC0L3RlCDwn5Ww77iPDQoNCg0KDQrwn4yYINCi0LXQvNGA0Y/QstCwINCy0LjRgNGW0YjQuNC70LAg0LfQsNC70LjRiNC40YLQuCDRgdCy0L7RlCDQv9GA0L7RgNC+0YbRgtCy0L4g8J+TnCDigJQg0YLQsNGU0LzQvdC1INGC0LAg0LfQsNCz0LDQtNC60L7QstC1LiDQhiDQu9C40YjQtSDRgtC+0Lkg0YXRgtC+INC/0LXRgNGI0LjQvCDQudC+0LPQviDRgNC+0LfQs9Cw0LTQsNGUIOKAlCDQvtGC0YDQuNC80LDRlCDQtNCw0YDRg9C90L7QuiDQvdC+0YfRliDwn4ySDQoNCg0KDQrwn5Wv77iPINCh0YPRgtGMINCz0YDQuDoNCg0KDQoNCvCfk5wg0J/QtdGA0LXQtCDQv9C+0YfQsNGC0LrQvtC8INCz0YDQuCDQktC10LTRg9GH0LAg0L7Qs9C+0LvQvtGI0YPRlCDQt9Cw0LPQsNC00LrRgy3Qv9GA0L7RgNC+0YbRgtCy0L4uDQoNCtCT0YDQsNCy0YbRliDQv9C+0YfQuNC90LDRjtGC0Ywg0YjRg9C60LDRgtC4INCy0ZbQtNC/0L7QstGW0LTRjC4NCg0K0JPRgNCw0LLQtdGG0YwsINGP0LrQuNC5INC/0LXRgNGI0LjQuSDQstGW0LTQs9Cw0LTQsNGUINC/0YDQsNCy0LjQu9GM0L3QviDQt9Cw0LPQsNC00LrRgyDigJQg0L7RgtGA0LjQvNCw0ZQ6DQoNCiAxKSDQhtC80YPQvdGW0YLQtdGCINC90LAg0L3QsNGB0YLRg9C/0L3RgyDQvdGW0YcuDQoNCtCG0LzRg9C90YPRgtC10YIg0LTRltGUINC70LjRidC1INC+0LTQvdGDINC90ZbRhywg0LTQsNC70ZYg4oCTINC90L7QstCwINC30LDQs9Cw0LTQutCwLCDRgtCwINC90L7QstC40Lkg0ZbQvNGD0L3RltGC0LXRgi4NCg0K8J+puCDQr9C60YnQviDQvdGW0YXRgtC+INC90LUg0LLQs9Cw0LTQsNGUIOKAlA0KDQrQvdGW0Ycg0L/RgNC+0YXQvtC00LjRgtGMINCx0LXQtyDQt9C80ZbQvSDRliDQsdC10Lcg0LfQsNGF0LjRgdGC0YMuDQoNCg0KDQrwn5SrINCU0J7Ql9CS0J7Qm9Cv0ITQotCs0KHQrzoNCg0K4pyU77iPINGB0YLQsNC90LTQsNGA0YLQvdGWINC00ZbRlyDRgNC+0LvQtdC5DQoNCuKclO+4jyDQsNC60YLQuNCy0L3QsCDRg9GH0LDRgdGC0Ywg0YMg0LLRltC00LPQsNC00YPQstCw0L3QvdGWDQoNCuKclO+4jyDQutC70LDRgdC40YfQvdC40Lkg0YTQvtGA0LzQsNGCINCz0YDQuA0KDQoNCg0KDQoNCuKame+4jyDQk9GA0LA6DQoNCuKdl++4jyDQkdC10Lcg0LfQvNGW0L0g0LzQtdGF0LDQvdGW0LrQuA0KDQrinZfvuI8g0JHQtdC3INC00L7QtNCw0YLQutC+0LLQuNGFINCx0LDRhNGW0LINCg0K4p2X77iPINCj0YHRliDRgNC+0LvRliDRg9Cy0ZbQvNC60L3QtdC90ZYNCg0K4p2X77iPINCf0YDQvtGA0L7RhtGC0LLQviDQndCQ0J/QoNCv0JzQoyDQv9C+0LLKvNGP0LfQsNC90LUg0Lcg0LPRgNC+0Y4gDQoNCg0KDQrwn4ySINCl0YLQviDQstGB0YLQuNCz0L3QtSDQv9C10YDRiNC40Lw/DQoNCtCl0YLQviDQv9GA0L7Rh9C40YLQsNGUINC80ZbQtiDRgNGP0LTQutCw0LzQuD8NCg0K0KXRgtC+INCy0YXQvtC/0LjRgtGM0YHRjyDQt9CwINGI0LDQvdGBINC/0LXRgNC10LbQuNGC0Lgg0L3RltGHPw0KDQoNCg0K8J+UriDQn9GA0L7RgNC+0YbRgtCy0L4g0LfQstGD0YfQuNGC0Ywg0LvQuNGI0LUg0YDQsNC3Lg0KDQrQhiDRh9C10LrQsNGUINC90LAg0YLQvtCz0L4sDQoNCtGF0YLQviDQvdC1INCx0L7Rl9GC0YzRgdGPINC00YPQvNCw0YLQuCDRiNCy0LjQtNGI0LUg0LfQsCDRgtC10LzRgNGP0LLRg+KApiDwn4yR4pyo",
    "8J+MkiDQotGD0YIg0L3RltGF0YLQviDQvdC1INC00LjQutGC0YPRlCDQv9GA0LDQstC40LvQsCDRgtCy0L7RlNGXINC60LvRj9GC0LLQuOKApg0KDQrRgtC4INC+0LHQuNGA0LDRlNGIINGX0Zcg0YHQsNC8Lg0KDQrQntC00L3QtSDRgNC10YfQtdC90L3Rjy4NCg0K0J7QtNC90LAg0L7QsdGW0YbRj9C90LrQsC4NCg0K0J7QtNC90LAg0L/QvtC80LjQu9C60LAg4oCUINGWINGC0Lgg0LfQvdC40LrQsNGU0YguIPCfkoANCg0K0KLQtdC80YDRj9Cy0LAg0L3QtSDQutCw0YDQsNGUINCy0LjQv9Cw0LTQutC+0LLQvi4NCg0K0JLQvtC90LAg0LrQsNGA0LDRlCDQt9CwINGB0LvQsNCx0LrRltGB0YLRjC4g8J+puA0KDQrQp9C4INCy0LjRgdGC0LDRh9C40YLRjCDRgtC+0LHRliDRgdC80ZbQu9C40LLQvtGB0YLRliDQstGW0LTQv9C+0LLRltGB0YLQuCDQt9CwINCy0LvQsNGB0L3QtSDRgdC70L7QstC+PyDwn5Wv8J+UpQ0KDQoNCg0K8J+Vr++4jyDQodGD0YLRjCDQs9GA0Lg6DQoNCvCfk5wg0J/QldCg0JXQlCDQn9Ce0KfQkNCi0JrQntCcINC60L7QttC10L0g0YPRh9Cw0YHQvdC40Log0LzQsNGUINC90LDQv9C40YHQsNGC0Lgg0LIg0YfQsNGCINC+0LTQvdGDINC+0LHRltGG0Y/QvdC60YMuDQoNCg0KDQrQndCw0L/RgNC40LrQu9Cw0LQ6DQoNCuKAlCDQvdC1INC80L7QstGH0LDRgtC4INCx0ZbQu9GM0YjQtSAyINGF0LLQuNC70LjQvQ0KDQrigJQg0L3QtSDQs9C+0LvQvtGB0YPQstCw0YLQuCDRgNCw0L3QtNC+0LzQvdC+DQoNCuKAlCDQvdC1INC/0LjRgdCw0YLQuCDigJwr4oCdDQoNCuKAlCDQvdC1INC/0ZbQtNGC0YDQuNC80YPQstCw0YLQuCDQutC+0L3QutGA0LXRgtC90L7Qs9C+INCz0YDQsNCy0YbRjw0KDQrimqDvuI8g0J/QvtGA0YPRiNC40LIg0L7QsdGW0YbRj9C90LrRgyDigJQg0L7QtNGA0LDQt9GDINCy0LjQsdGD0LLQsNGU0Ygg8J+SgA0KDQoo0LrQvtC80LDQvdC00LAg8J+RiSAvbGVhdmUpDQoNCg0KDQrinZfvuI8g0J7QsdGW0YbRj9C90LrQsCDQvNCw0ZQg0LHRg9GC0Lgg0YDQtdCw0LvRjNC90L7RjiDRgtCwINC/0LXRgNC10LLRltGA0Y/RlNGC0YzRgdGPINCy0LXQtNGD0YfQvtGODQoNCuKdl++4jyDQndC10LzQvtC20LvQuNCy0ZYg0LDQsdC+INCw0LHRgdGD0YDQtNC90ZYg0LrQu9GP0YLQstC4INC90LUg0L/RgNC40LnQvNCw0Y7RgtGM0YHRjw0KDQoNCg0K4pqZ77iPINCT0YDQsCDRgdGC0LDQvdC00LDRgNGC0L3QsDoNCg0K4oCiINCj0YHRliDRgNC+0LvRliDQsNC60YLQuNCy0L3Rlg0KDQrigKIg0JHQtdC3INCx0LDRhNGW0LINCg0KDQoNCtCi0LXQvNGA0Y/QstCwINC30LDQutGA0LjQstCw0ZQg0LPRgNGDLg0KDQrQkNC70LUg0L/QsNC84oCZ0Y/RgtGMIOKAlCDQt9Cw0LvQuNGI0LDRlNGC0YzRgdGPLiDwn5Sl",
    "8J+MkSDQoyDRgtC10LzRgNGP0LLRliDQvdC10LHQtdC30L/QtdGH0L3QviDQvdC1INC70LjRiNC1INC80L7QstGH0LDRgtC4Lg0KDQrQndC10LHQtdC30L/QtdGH0L3QviDQv9C+0LzQuNC70Y/RgtC40YHRjy4NCg0K8J+MmCDQptGW0ZTRlyDQvdC+0YfRliDQvNCw0YTRltGPINC90LUg0L/RgNC+0YHRgtC+INGB0YLRgNGW0LvRj9GUIC0NCg0K0LLQvtC90LAg0LzQuNGB0LvQuNGC0YwuDQoNCtCa0YPQu9GPINC70LXRgtC40YLRjCDRgNCw0LfQvtC8INGW0Lcg0L/RltC00L7Qt9GA0L7Rji4NCg0K0IYg0Y/QutGJ0L4g0LfQtNC+0LPQsNC0INCy0LjRj9Cy0LjRgtGM0YHRjyDRgtC+0YfQvdC40LwgLQ0KDQrQvdGW0Ycg0LfQsNCx0LXRgNC1INCx0ZbQu9GM0YjQtSwg0L3RltC2INC+0YfRltC60YPQstCw0LvQuC4NCg0K0JHQviDRltC90LrQvtC70Lgg0L3QsNC50YHRgtGA0LDRiNC90ZbRiNC1IC0NCg0K0YbQtSDQutC+0LvQuCDQstC+0YDQvtCzINC30L3QsNGULCDRhdGC0L4g0YLQuC4NCg0KDQoNCvCfla/vuI8g0KHRg9GC0Ywg0LPRgNC4Og0KDQoNCg0K8J+MmSDQndCG0KcNCg0K0JTQvtC9INC/0LjRiNC1INCyINCf0J8g0LLQtdC00YPRh9C+0LzRgzoNCg0K4oCiINCa0L7Qs9C+INCy0LHQuNCy0LDRjtGC0YwNCg0K4oCiINCv0LrRgyDRgNC+0LvRjCwg0L3QsCDQudC+0LPQviDQtNGD0LzQutGDLCDQvNCw0ZQg0YbQtdC5INCz0YDQsNCy0LXRhtGMDQoNCtCd0LDQv9GA0LjQutC70LDQtDoNCg0KQNGO0LcgLSDQtNGD0LzQsNGOINGG0LUg0LvRltC60LDRgA0KDQoNCg0K4piA77iPINCU0JXQndCsDQoNCtCv0LrRidC+INGA0L7Qu9GMINCy0LHQuNGC0L7Qs9C+INCz0YDQsNCy0YbRjyDRgdC/0ZbQstC/0LDQu9CwINC3INC/0YDQuNC/0YPRidC10L3QvdGP0Lwg0LzQsNGE0ZbRlyAtDQoNCtC80LDRhNGW0Y8g0L7RgtGA0LjQvNGD0ZQg0L/RgNCw0LLQviDQvtCx0YDQsNGC0Lgg0YnQtSDQvtC00L3QvtCz0L4g0LPRgNCw0LLRhtGPLCDRj9C60LjQuSDQstC40LHRg9C00LUuDQoNCvCflKog0JLRltC00LHRg9Cy0LDRlNGC0YzRgdGPINCf0L7QtNCy0ZbQudC90LjQuSDQo9C00LDRgC4NCg0K0K/QutGJ0L4g0YDQvtC70Ywg0J3QlSDRgdC/0ZbQstC/0LDQu9CwINC3INC/0ZbQtNC+0LfRgNC+0Y4gLQ0KDQrQvdGW0Ycg0LfQsNCx0LjRgNCw0ZQg0LvQuNGI0LUg0L7QtNC90YMg0LbQtdGA0YLQstGDLg0KDQrQk9C+0LvQvtGB0YPQstCw0L3QvdGPINC/0YDQvtGF0L7QtNC40YLRjCDQsdC10Lcg0LfQvNGW0L0uDQoNCg0KDQrwn5SrINCU0J7Ql9CS0J7Qm9Cv0ITQotCs0KHQrzoNCg0K4pyU77iPINCg0LDQvdC00L7QvCANCg0K4pyU77iPINGB0YLRgNCw0YLQtdCz0ZbRjyDRgtCwINCw0L3QsNC70ZbRgtC40LrQsA0KDQoNCg0K4pqZ77iPINCT0YDQsDoNCg0K4p2X77iPINCR0LXQtyDQsdCw0YTRltCyDQoNCuKdl++4jyDQlNC+0LTQsNGC0LrQvtCy0LAg0LbQtdGA0YLQstCwINC80L7QttC70LjQstCwINC70LjRiNC1INC/0YDQuCDRgtC+0YfQvdC+0LzRgyDQstCz0LDQtNGD0LLQsNC90L3RliDRgNC+0LvRlg0KDQoNCg0KDQoNCvCfjJIg0KfQuCDQvdCw0LLQsNC20LjRgtGM0YHRjyDQlNC+0L0g0YDQuNC30LjQutC90YPRgtC4INC30LTQvtCz0LDQtNC+0Lw/DQoNCtCn0Lgg0YHRgtCw0L3QtSDQvdGW0Ycg0YTQsNGC0LDQu9GM0L3QvtGOINC00LvRjyDQtNCy0L7RhT8NCg0K8J+ptiDQoyDRhtGW0Lkg0LPRgNGWINCy0LjQttC40LLQsNGUINC90LUg0LvQuNGI0LUg0YHQuNC70YzQvdC40LnigKYNCg0K0LAg0YLQvtC5LCDRhdGC0L4g0LTRg9C80LDRlCDRgtC+0YfQvdGW0YjQtS4=",
    "4o+wINCp0L7RgdGD0LHQvtGC0LggDQoNCvCfkpgg0KnQviDRhtC1INC30LAg0YDQtdC20LjQvD8NCg0K0JHQvtGCINCy0LjQv9Cw0LTQutC+0LLQviDQvtCx0LjRgNCw0ZQg0LLQsNC8INC/0LDRgNGDINCyINC/0L8uDQoNCtCS0LDRiNCwINC80ZbRgdGW0Y8g4oCUINCy0LjQttC40YLQuCDRgtCwINC/0YDQuNCy0LXRgdGC0Lgg0YHQstC+0Y4g0L/QvtC70L7QstC40L3QutGDINC00L4g0L/QtdGA0LXQvNC+0LPQuC4NCg0K0KLRg9GCINGD0YHQtSDQstC40YDRltGI0YPRlCDRgdGC0YDQsNGC0LXQs9GW0Y8sINGF0LjRgtGA0ZbRgdGC0Ywg0ZYg0LTQvtCy0ZbRgNCwIPCfkYANCg0K0JPQvtC70L7QstC90LUg4oCUINCz0YDQsNGC0Lgg0YDQsNC30L7QvCDRliDQvdC1INCy0LjQtNCw0YLQuCDRgdCy0ZbQuSDRgdC+0Y7Qty4NCg0KDQoNCtCf0YDQsNCy0LjQu9CwINGA0LXQttC40LzRgzogDQoNCvCfpI0g0JzRltC90ZbQvNGD0LwgNiDQs9GA0LDQstGG0ZbQsg0KDQrwn6SN0K/QutGJ0L4g0LrRltC70YzQutGW0YHRgtGMINGD0YfQsNGB0L3QuNC60ZbQsiDQvdC10L/QsNGA0L3QsCDigJQg0YDQtdC20LjQvCDQsNCy0YLQvtC80LDRgtC40YfQvdC+INCy0LjQvNC40LrQsNGU0YLRjNGB0Y8NCg0K8J+kjdCf0LXRgNC10LzQvtC20L3QsCDQv9Cw0YDQsCDQvtGC0YDQuNC80YPRlCDQv9C+IDQwINGW0LPRgNC+0LLQuNGFINCz0YDQuNCy0LXQvdGMDQoNCvCfpI3QnNC+0LbQu9C40LLQsCDQvdGW0YfQuNGPINCw0LHQviDQv9C10YDQtdC80L7Qs9CwINC+0LTQvdGW0ZTRlyDRh9C4INC90LDQstGW0YLRjCDQtNCy0L7RhSDQv9Cw0YANCg0K8J+kjdCv0LrRidC+INCyINC/0LXRgNGI0YMg0L3RltGHINCy0LjQsdGD0LLQsNGO0YLRjCDQtNCy0L7RlCDigJQg0ZfRhdC90ZYg0L/QvtC70L7QstC40L3QutC4INGB0YLQsNGO0YLRjCDQvdC+0LLQvtGOINC/0LDRgNC+0Y4NCg0KDQoNCuKAvO+4jyDQotGA0LjQvNCw0LnRgtC1INGB0LLQvtGOINC/0LDRgNGDINCyINGB0LXQutGA0LXRgtGWDQoNCuKAvO+4jyDQlNC+0LfQstC+0LvQtdC90LAg0LDQutGC0LjQstC90LAg0LPRgNCwINCyINC/0L8NCg0KDQoNCvCfmqvinYwg0JLQsNC20LvQuNCy0L46INC90LDQstC80LjRgdC90L4g0LfQu9C40LLQsNGC0Lgg0LDQsdC+INC/0ZbQtNGB0YLQsNCy0LvRj9GC0Lgg0YHQstC+0Y4g0L/QvtC70L7QstC40L3QutGDINC30LDQsdC+0YDQvtC90LXQvdC+IOKAlCDQt9CwINGG0LUg0LHRg9C00LUg0L/QvtC60LDRgNCw0L3QvdGPLg0KDQrQk9C+0YLRg9C50YLQtSDQvdC10YDQstC4LCDQtNC+0LLRltGA0YMg0YLQsCDRhdC+0LvQvtC00L3QuNC5INGA0L7Qt9GD0Lwg4oCUDQoNCtGB0YzQvtCz0L7QtNC90ZYg0LLQuNGA0ZbRiNGD0ZQg0L3QtSDRgtGW0LvRjNC60Lgg0YDQvtC70YwsINCwINC5INGB0L7RjtC3IOKdpO+4jw==",
    "8J+XkyDQmtC+0LvQuD8NCg0K0KnQvtC90LXQtNGW0LvRliDRhtGW0LvQuNC5INC00LXQvdGMIOKPsyDigJQg0LzQsNC60YHQuNC80YPQvCDQvdCw0L/RgNGD0LPQuCwg0LTRgNCw0LnQstGDINGC0LAg0Y/RgdC60YDQsNCy0LjRhSDQvNC+0LzQtdC90YLRltCyINGDINCz0YDRli4NCg0K0JLQv9GA0L7QtNC+0LLQtiDRg9GB0YzQvtCz0L4g0LTQvdGPINC60LvQsNGB0LjRh9C90ZYg0ZbQs9GA0L7QstGWINC/0YDQsNCy0LjQu9CwINCc0LDRhNGW0Zcg0L3QtSDQtNGW0Y/RgtC40LzRg9GC0YwsINGC0L7QtiDQs9C+0YLRg9C50YLQtdGB0Y8g0LTQviDRgdC80ZbQu9C40LLQuNGFINGF0L7QtNGW0LIsINC90LXQvtGH0ZbQutGD0LLQsNC90LjRhSDRgNGW0YjQtdC90Ywg0ZYg0YHQv9GA0LDQstC20L3RjNC+0LPQviDQstC40LHRg9GF0YMg0LXQvNC+0YbRltC5IPCfkqPwn5iPDQoNCg0KDQrinZcg0JLQkNCW0JvQmNCS0J46DQoNCtCf0L7Qv9GA0Lgg0YHQstC+0LHQvtC00YMg0LIg0YHQsNC80ZbQuSDQs9GA0ZYsINC/0YDQsNCy0LjQu9CwINGH0LDRgtGDINC30LDQu9C40YjQsNGO0YLRjNGB0Y8g0L3QtdC30LzRltC90L3QuNC80Lgg8J+SrA0KDQrQn9GA0L7RgdC40LzQviDQutC+0LbQvdC+0LPQviDQtNC+0YLRgNC40LzRg9Cy0LDRgtC40YHRjyDQv9C+0LLQsNCz0Lg6DQoNCuKAlCDQsdC10Lcg0L7QsdGA0LDQtyDwn5qrDQoNCuKAlCDQsdC10Lcg0L/QtdGA0LXRhdC+0LTRltCyINC90LAg0L7RgdC+0LHQuNGB0YLQvtGB0YLRliDwn5mF4oCN4pmC77iPDQoNCuKAlCDQsdC10Lcg0L/RgNC40L3QuNC20LXQvdGMINGWINC60L7QvdGE0LvRltC60YLRltCyIOKalu+4jw0KDQoNCg0K0JzQuCDRgdGC0LLQvtGA0Y7RlNC80L4g0L/RgNC+0YHRgtGW0YAsINC00LUg0YbRltC60LDQstC+LCDQs9Cw0YDRj9GH0LUg0Lkg0LLQvtC00L3QvtGH0LDRgSDQsdC10LfQv9C10YfQvdC+INC00LvRjyDQstGB0ZbRhSDwn6SN4pyoDQoNCg0KDQrQpdC+0YfQtdC80L4g0LHQsNGH0LjRgtC4INC80LDQutGB0LjQvNCw0LvRjNC90YMg0LDQutGC0LjQstC90ZbRgdGC0Ywg8J+agCwg0YLQvtC80YMg0LfQstGW0LvRjNC90Y/QudGC0LUg0YHQstGW0Lkg0LTQtdC90YwsINC30LDQv9GA0L7RiNGD0LnRgtC1INC00YDRg9C30ZbQsiDwn5GlINGWINCz0L7RgtGD0LnRgtC10YHRjyDQtNC+INC/0L7QtNGW0ZcsINC/0YDQviDRj9C60YMg0YnQtSDQtNC+0LLQs9C+INCz0L7QstC+0YDQuNGC0LjQvNGD0YLRjCDwn5akDQoNCtCR0YPQtNC1INC/0L4t0YHQv9GA0LDQstC20L3RjNC+0LzRgyDQs9Cw0YDRj9GH0LUg8J+UpfCflKXwn5Sl",
];
const eventsData = Object.fromEntries(
    encodedEvents.map((val, i) => [
        "shadow" + (i + 1),
        val ? b64(val) : ""
    ])
);
document.addEventListener("DOMContentLoaded", () => {
    document.querySelectorAll(".description").forEach(el => {
        const key = el.dataset.event;
        if (eventsData[key]) {
            el.innerText = eventsData[key];
        }
    });

    resetBotSystems();
    renderBots();
    setupBotModal();
    setupGameFocusMode();
    syncExpandablePanels();
});
window.addEventListener("resize", syncExpandablePanels);
document.addEventListener("keydown", e => {
    if (e.key === "Escape") {
        closeBotModal();
    }
});
/*Watermark*/
console.log(
    "%cENAMORADO_DE_UN_SUENO_2026_OFFICIAL_BUILD",
    "color:#d14b5a;font-weight:bold;font-size:14px"
);
/*BOT HUB*/
const bots = [
    {
        name: "Мафія",
        avatar: "assets/MafiaBot.jpg",
        link: "https://t.me/MafiaUaBot",
        tagline: "Керує грою від роздачі ролей до визначення переможця",
        description: "Класична соціальна гра з прихованими ролями, де гравці через обговорення, підозри та голосування намагаються знайти противників. Тут важлива не тільки логіка, а й вміння читати людей.",
        flow: [
            "🎭 Кожен отримує приховану роль",
            "🌙 Вночі ролі виконують свої дії",
            "☀️ Вдень гравці обговорюють і підозрюють",
            "🗳 Голосування вирішує, кого вигнати",
            "🔁 Гра триває до перемоги однієї сторони"
        ],
        tips: [
            "Не поспішай довіряти словам",
            "Спостерігай за поведінкою",
            "Брешуть не тільки мафія 😏",
            "Командна гра вирішує більше, ніж індивідуальна"
        ],
        usage: [
            "🎮 Запустити гру (/game)",
            "👥 Приєднатися до гри (/join)",
            "🚪 Вийти з гри (/leave)",
            "⏱ Переглянути час (/time)",
            "🛑 Зупинити гру (/stop)",
            "⏳ Додати час (/extend)",
            "⚙️ Налаштування (/settings)"
        ]
    },
    {
        name: "Truth Ukrainian Bot",
        avatar: "assets/TruthUkrainianBot.jpg",
        link: "https://t.me/TruthUkrainian_Bot",

        tagline: "Платформа ігор та інтерактиву в чаті",

        description: "Багатофункціональний бот, який об’єднує кілька ігор, систему прогресу та соціальні механіки. Підходить як для швидких розваг, так і для довготривалої активності в чаті.",

        flow: [
            "🎮 Запускаєш гру",
            "👥 Гравці приєднуються",
            "🧩 Обираєте режим",
            "🔄 Проходить ігровий цикл",
            "🏆 Отримуєте результат",
            "🤖 AI-чат (Premium)"
        ],

        tips: [
            "Грай не один — бот розкривається в компанії",
            "Спробуй різні режими",
            "Рейтинг мотивує повертатись",
            "Це не одна гра — це система"
        ],

        // 👇 ХОВАЄМО ПІД КНОПКИ

        deep: {
            features: [
                "🎮 Кілька ігор в одному боті",
                "📊 Глобальна та локальна статистика",
                "🍉 Міні-гра з кавунчиками",
                "🃏 Повноцінний UNO",
                "⚙️ Гнучкі налаштування",
                "🤖 AI-чат (Premium)"
            ],

            games: [
                {
                    name: "Правда або Дія",
                    description: "Питання або завдання",
                },
                {
                    name: "Правда або Фейк",
                    description: "Вгадування фактів",
                },
                {
                    name: "Хто Я?",
                    description: "Вгадування персонажа",
                },
                {
                    name: "UNO",
                    description: "Карткова гра з режимами",
                }
            ],

            extra: [
                "🍉 Кавунчики",
                "📈 Рейтинг",
                "🌍 Глобальна статистика",
                "👑 Premium"
            ],

            usage: [
                "🎮 Відкрити меню ігор (/gmstart)",
                "🤖 Написати AI (тру ботик)",
                "👥 Приєднатися до гри (/gmjoin)",
                "🚪 Вийти з гри (/gmleave)",
                "🛑 Зупинити гру (/gmstop)",
                "📊 Переглянути статистику (/truthstats)",
                "👤 Відкрити профіль (/truthprofile)",
                "⚙️ Налаштування (/truthsettings)",
                "🍉 Відкрити кавунчики (/mykavun)"
            ]
        }
    },
    {
        name: "Bunker | TruthUk",
        avatar: "assets/BunkerUKR.jpg",
        link: "https://t.me/OfBunkerUA_bot",

        tagline: "Соціальна гра на виживання та переконання",

        description: "Гра, де рішення приймають не правила, а люди. Кожен гравець отримує випадкову роль і характеристики та повинен довести, що саме він заслуговує місце в бункері після апокаліпсису.",

        flow: [
            "🎲 Генерується сценарій апокаліпсису",
            "👤 Гравці отримують характеристики",
            "🔓 Відкривається інформація про себе",
            "💬 Обговорення та переконання",
            "🗳 Голосування і виключення",
            "🔄 Раунди повторюються до фіналу"
        ],

        tips: [
            "Говори впевнено — навіть слабку роль можна продати",
            "Не відкривай усе одразу",
            "Слухай інших — слабкі аргументи видають",
            "Гра виграється словами, а не характеристиками",
            "Іноді краще виглядати корисним, ніж бути ним 😏"
        ],

        // 👇 ХОВАЄМО ПІД КНОПКИ

        deep: {
            features: [
                "🎲 Випадкові ролі та характеристики",
                "🌍 Динамічні сценарії апокаліпсису",
                "🧠 Соціальна стратегія та логіка",
                "💬 Живе обговорення між гравцями",
                "🗳 Система голосування",
                "⏱ Таймінги та автоматизація ботом"
            ],

            games: [
                {
                    name: "Класичний Bunker",
                    description: "Соціальна гра з вибуванням та обговоренням"
                }
            ],

            extra: [
                "📊 Неповна інформація",
                "⚖️ Вибір що і коли відкривати",
                "🎯 Сильна роль не гарантує перемогу",
                "🔥 Тиск на активність гравців"
            ],

            usage: [
                "🎮 Запустити гру (/game)",
                "👥 Приєднатися (/join)",
                "🚪 Вийти (/leave)",
                "⏳ Продовжити набір (/extend)",
                "🛑 Зупинити гру (/stop)",
                "⏸ Пауза (/pause)",
                "▶️ Продовжити (/resume)",
                "⚙️ Налаштування (/settings)",
                "👢 Кікнути гравця (адмін) (/kick)"
            ]
        }
    },
    {
        "name": "Koтik | TruthUk",
        "avatar": "assets/KotykUKR.jpg",
        "link": "https://t.me/gavgames_bot",

        "tagline": "Соціальний бот для фанового життя чату",

        "description": "Багатофункціональний чат-бот, який поєднує ігри, рольову взаємодію та AI-асистента. Його головна мета — зробити спілкування в чаті більш живим, емоційним і інтерактивним.",

        "flow": [
            "💬 Взаємодієш з ботом у чаті",
            "🎮 Запускаєш гру або активність",
            "👥 Інші гравці підключаються",
            "🔄 Відбувається взаємодія (ходи / RP / реакції)",
            "🏁 Отримуєте результат або фан"
        ],

        "tips": [
            "Використовуй бота в активному чаті — він розкривається через людей",
            "Не обмежуйся іграми — спробуй RP і соціальні функції",
            "Експериментуй — тут багато неочевидних механік",
            "Більше взаємодії = більше фану",
            "Це не бот-команда, це частина атмосфери чату 😺"
        ],

        "rp_commands": [
            "бу",
            "вдарити",
            "вилизати",
            "виїбати",
            "дроч",
            "мяу",
            "нагодувати",
            "обійняти",
            "погладити",
            "покусати",
            "поцілувати",
            "притиснути",
            "трахнути",
            "цьом",
            "чай",
            "шшш"
        ],

        //"mur_commands": {
        //    "commands": [
        //        { "command": "мур", "description": "замурчати" },
        //        { "command": "мур @username", "description": "замурчати комусь" },
        //        { "command": "мур (reply)", "description": "замурчати у відповідь" },
        //        { "command": "хвіст", "description": "виростити або втратити хвіст" }
        //    ],
        //    "cooldowns": {
        //        "mur": "120 секунд на користувача",
        //        "tail": "1 раз на годину"
        //    }
        //},

        "deep": {
            "features": [
                "🎮 Різні типи ігор",
                "💬 RP та соціальні команди",
                "🤖 AI-спілкування та відповіді",
                "📊 Рейтинги та профілі",
                "🌿 Внутрішня економіка",
                "⚙️ Адмін-налаштування"
            ],

            "games": [
                {
                    "name": "Хрестики-Нолики",
                    "description": "Класична гра 3x3 проти іншого гравця"
                },
                {
                    "name": "Мемчики",
                    "description": "Обери найкращий мем під ситуацію"
                },
                {
                    "name": "Міні-Ігри 🎲",
                    "description": "Короткі розваги без складної структури"
                }
            ],

            "extra": [
                "💕 RP-взаємодія між гравцями",
                "💍 Система шлюбів",
                "🤖 AI-пам’ять та діалоги",
                "⏰ Нагадування та допомога",
                "👤 Профіль гравця",
                "🌍 Активність у чаті як центр всього"
            ],

            "usage": [
                "🚀 Відкрити меню (/start)",
                "👤 Відкрити профіль (/profile)",
                "🏆 Переглянути топ (/top)",
                "💬 Переглянути топ чату (/topchat)",
                "⚙️ Відкрити налаштування (/settings)",
                "💎 AI преміум (/prem)",

                "🎮 Почати гру (/newgame)",
                "⛔ Зупинити гру (/stopcat)",
                "⚡ Швидко зупинити гру (/nax)",
                "🚪 Вийти з гри (/leave)",

                "💍 Шлюб (/marriage)",
                "⏰ Нагадування (/reminders)",

                "💕 Взаємодія з гравцями (RP-команди)",
                "😼 Соціальні реакції (мур, хвіст)",

                "🎰 Відкрити казино (Казино сума*)"
            ]
        }
    },
    {
        name: "Кеш-Бос",
        avatar: "assets/CashBoss.jpg",
        link: "https://t.me/StarsHelper1_Bot",

        tagline: "Економіка та валюта всередині чату",

        description: "Telegram-бот, який додає в чат повноцінну економічну систему: користувачі заробляють валюту за активність, витрачають її в магазині та можуть ризикувати в азартних іграх для швидкого прибутку або втрат.",

        flow: [
            "💬 Спілкуєшся в чаті та отримуєш валюту",
            "🎮 Береш участь в іграх або івентах",
            "💰 Заробляєш і накопичуєш коїни",
            "🛒 Витрачаєш у магазині або взаємодієш з іншими",
            "📈 Зростаєш у рейтингу багатих гравців"
        ],

        tips: [
            "Не тримай всі гроші — ризик може як підняти, так і обнулити",
            "Активність у чаті — стабільніший дохід, ніж азарт",
            "Використовуй економіку розумно — це ще й вплив",
            "Передавай валюту — це створює зв’язки",
            "Blackjack — це швидкий шлях або в топ, або в нуль 😏"
        ],

        // 👇 ХОВАЄМО ПІД КНОПКИ

        deep: {
            features: [
                "💰 Внутрішня валюта (коїни)",
                "📈 Рейтинг найбагатших гравців",
                "🛒 Магазин з різними типами покупок",
                "🎮 Ігрові механіки для заробітку",
                "🔁 Передача валюти між гравцями",
                "⚙️ Інтеграція з чат-активністю"
            ],

            games: [
                {
                    name: "Blackjack",
                    description: "Карткова гра на ставку проти бота"
                },
                {
                    name: "Кубик",
                    description: "Підкидання кубика"
                },
            ],

            extra: [
                "🎭 Соціальні бонуси (статуси, префікси)",
                "⚖️ Вплив на модерацію через економіку",
                "🕵️ Анонімні взаємодії",
                "💸 Донат або купівля валюти",
                "🌍 Економіка як центр взаємодії"
            ],

            usage: [
                "💰 Переглянути баланс (/me)",
                "🃏 Грати в Blackjack (/bj)",
                "🛒 Відкрити магазин (/shop)",
                "💸 Передати коїни (/give_coins)",
                "🏆 Переглянути топ багатих (/top_rich)",
                "📊 Відкрити профіль (/start)",
                "🎲 Кинути кубик (кубик)"
            ]
        }
    },
    {
        name: "Кодові імена",
        avatar: "assets/CodenamesBot.jpg",
        link: "https://t.me/codenames_ua_bot", // якщо інший — заміниш

        tagline: "Командна гра на асоціації та синергію",

        description: "Командна гра, де один гравець дає асоціації, а інші намагаються знайти правильні слова серед багатьох варіантів. Перемагає команда, яка краще розуміє одне одного та уникає критичних помилок.",

        flow: [
            "👥 Гравці діляться на команди",
            "🧩 Генерується поле зі словами",
            "🧠 Один дає підказку (слово + число)",
            "💬 Команда обговорює варіанти",
            "🎯 Вибір слів на полі",
            "🔄 Хід переходить до іншої команди"
        ],

        tips: [
            "Думай як твоя команда, а не як ти",
            "Одна хороша асоціація може вирішити гру",
            "Не жадничай — більше слів = більше ризику",
            "Слухай логіку інших гравців",
            "Іноді найочевидніше — це пастка 😏"
        ],

        // 👇 ХОВАЄМО ПІД КНОПКИ

        deep: {
            features: [
                "🧠 Асоціативний геймплей",
                "👥 Командна взаємодія",
                "🎯 Ризик та стратегія вибору",
                "🧩 Генерація ігрового поля",
                "🤖 Автоматичне ведення гри",
                "⚙️ Гнучкість режимів"
            ],

            games: [
                {
                    name: "Класичний режим",
                    description: "Командна гра з підказками та відгадуванням"
                }
            ],

            extra: [
                "🔍 Неповна інформація для гравців",
                "⚖️ Баланс між ризиком і точністю",
                "🧠 Інтерпретація підказок",
                "👥 Синергія команди",
                "🚫 Обмеження на підказки"
            ],

            usage: [
                "🎮 Запустити гру (/game)",
                "👥 Приєднатися до команди (/join)",
                "🚪 Вийти з гри (/leave)",
                "💡 Дати підказку (/hint)",
                "🎯 Обрати слово (/pick)",
                "⚙️ Налаштування (/settings)"
            ]
        }
    },
    {
        name: "Crocodile",
        avatar: "assets/KrokoBot.jpg",
        link: "https://t.me/croco_ua_bot", // якщо інший — заміниш

        tagline: "Швидкі ігри на реакцію та відгадування",

        description: "Telegram-бот для динамічних групових ігор, де все вирішує швидкість, уважність і реакція. Бот виступає як автоматичний ведучий, генерує завдання та миттєво визначає переможців у кожному раунді.",

        flow: [
            "🎮 Обираєш режим (/w, /math, /flags)",
            "🤖 Бот генерує завдання",
            "⌨️ Гравці відповідають у чаті",
            "⚡ Хто перший — той отримує очки",
            "🔄 Починається наступний раунд",
            "🏆 Формується рейтинг"
        ],

        tips: [
            "Швидкість важливіша за ідеальність",
            "Пиши коротко — це економить секунди",
            "Слідкуй за таймером",
            "Чим більше раундів — тим більше шансів вирватись в топ",
            "Це гра не про знання, а про реакцію ⚡"
        ],

        // 👇 ХОВАЄМО ПІД КНОПКИ

        deep: {
            features: [
                "⚡ Швидкі раундові ігри",
                "🤖 Автоматичний ведучий",
                "📊 Локальна статистика чатів",
                "🏆 Рейтинг гравців",
                "⚙️ Налаштування для адміністраторів",
                "💬 Соціальні механіки (шлюби)"
            ],

            games: [
                {
                    name: "Крокодил",
                    description: "Вгадування слова за описом"
                },
                {
                    name: "Математика",
                    description: "Рішення прикладів на швидкість"
                },
                {
                    name: "Прапори",
                    description: "Вгадування країн за прапором"
                }
            ],

            extra: [
                "📈 Топ гравців і чатів",
                "⏱ Динамічні таймери",
                "🎯 Різні типи завдань",
                "💍 Система шлюбів",
                "🔁 Безперервні раунди"
            ],

            usage: [
                "🐊 Запустити гру зі словами (/w)",
                "🧠 Запустити математику (/math)",
                "🌍 Запустити прапори (/flags)",
                "📊 Переглянути статистику (/stats)",
                "🏆 Переглянути топ (/top)",
                "⚙️ Налаштування (/ksettings)"
            ]
        }
    },
    {
        name: "Sunflower Stats",
        avatar: "assets/SoniashnykBot.jpg",
        link: "https://t.me/soniashnyk_statistics_bot",

        tagline: "Аналітика та статистика для чатів",

        description: "Бот для збору, обробки та візуалізації даних у чаті. Перетворює активність або результати в зрозумілі звіти, рейтинги та таблиці.",

        flow: [
            "📥 Збираються дані з чату або ігор",
            "🧠 Обробка та агрегація",
            "📊 Генерація статистики",
            "📄 Формування звітів",
            "📤 Вивід у зручному форматі"
        ],

        tips: [
            "Чим більше даних — тим цікавіша аналітика",
            "Використовуй для відстеження активності",
            "Рейтинги добре мотивують користувачів",
            "Експорт допомагає працювати з даними поза Telegram"
        ],

        deep: {
            features: [
                "📊 Збір статистики",
                "📈 Рейтинги та метрики",
                "📄 Генерація звітів",
                "📤 Експорт (CSV / таблиці)",
                "🧠 Агрегація даних"
            ],

            games: [],

            extra: [
                "🧮 Середні значення",
                "📊 Табличний формат",
                "🌍 Локальна аналітика чату"
            ],

            usage: [
                "📊 Переглянути свою статистику (!йа)",
                "👤 Переглянути статистику гравця (!ти)",
                "📈 Переглянути статистику чату (Стата)",
                "🏆 Переглянути топ чату (Стата вся)",
                "📅 Статистика за тиждень (Стата тиждень)",
                "📆 Статистика за місяць (Стата місяць)",
                "⚙️ Налаштування (/settings)"
            ]
        }
    },
    //{
    //    name: "BloodNexus | Bot",
    //    link: "https://t.me/bloodnexus_bot",
    //    type: "social",
    //    tagline: "RP, взаємодія та адміністрування",
    //    description: "Бот для рольової взаємодії, соціальних механік та управління чатом.",
    //    flow: [
    //        "🎭 Використання RP-команд",
    //        "💬 Взаємодія між гравцями",
    //        "⚙️ Адмін-функції",
    //        "📊 Контроль активності",
    //        "🔁 Постійна соціальна динаміка"
    //    ],
    //    tips: [
    //        "Працює через reply",
    //        "RP = основа бота",
    //        "Комбінуй з іншими ботами",
    //        "Добре заходить у активних чатах"
    //    ]
    //},
    //{
    //    name: "Luci",
    //    link: "https://t.me/liutsyk_bot",
    //    type: "social",
    //    tagline: "Соціалка, економіка та фан",
    //    description: "Бот, який поєднує внутрішню валюту, соціальні механіки та ігри між чатами.",
    //    flow: [
    //        "💰 Отримуєш валюту",
    //        "💬 Взаємодієш з іншими",
    //        "💍 Соціальні функції (шлюби)",
    //        "🎮 Ігри та активності",
    //        "🌐 Міжчатова взаємодія"
    //    ],
    //    tips: [
    //        "'Гріши' регулярно",
    //        "Соціалка важливіша за гроші",
    //        "Використовуй взаємодію з людьми",
    //        "Бот розкривається в активних чатах"
    //    ],
    //    usage: [
          //  "🎮 Start a new game (/newgame)",
          //  "👥 Join interactions (/join)",
          //  "🚪 Leave activity (/leave)",
          //  "💍 Create relationship (/marriage)",
          //  "🔮 Make prediction (/prediction)",
          //  "🎰 Play casino (/casino)",
          //  "🌦 Check weather (/weather)",
          //  "⚙️ Open settings (/settings)"
          //]
    //},
    //{
    //    name: "Rose",
    //    avatar: "assets/MissRoseBot.jpg",
    //    link: "https://t.me/MissRose_bot",

    //    tagline: "Потужна система модерації чату",

    //    description: "Один із найпопулярніших модераційних ботів, який автоматизує контроль за чатом: від антиспаму до складних систем правил і санкцій.",

    //    flow: [
    //        "👀 Моніторинг повідомлень",
    //        "⚠️ Виявлення порушень",
    //        "🔧 Застосування правил",
    //        "🚫 Санкції (mute / ban / warn)",
    //        "📊 Фіксація в системі"
    //    ],

    //    tips: [
    //        "Налаштуй фільтри під свій чат",
    //        "Не роби правила занадто жорсткими",
    //        "Слідкуй за false positives",
    //        "Використовуй warns як м’яку систему контролю"
    //    ],

    //    deep: {
    //        features: [
    //            "🛡 Антиспам і антифлуд",
    //            "🤖 Автоматична модерація",
    //            "📋 Система попереджень",
    //            "🔍 Regex-фільтри",
    //            "⚙️ Персональні налаштування чату"
    //        ],

    //        games: [],

    //        extra: [
    //            "👮 Ролі (admin / moderator / user)",
    //            "🧠 Stateful логіка",
    //            "📊 Збереження порушень",
    //            "⚠️ Обробка рейдів"
    //        ],

    //        commands: [
    //            "/warn",
    //            "/mute",
    //            "/ban",
    //            "/kick",
    //            "/filters"
    //        ]
    //    }
    //},
    {
        name: "Szczekacz",
        avatar: "assets/ZazyvalaBot.jpg",
        link: "https://t.me/zazyvalabot",

        tagline: "Інструмент для росту та залучення аудиторії",

        description: "Бот для просування чатів через інвайти, парсинг аудиторії та розсилки. Орієнтований на швидке масштабування спільнот.",

        flow: [
            "🔍 Збір аудиторії",
            "📥 Парсинг користувачів",
            "📨 Масові інвайти або повідомлення",
            "📈 Ріст чату"
        ],

        tips: [
            "Не зловживай — ризик блокування високий",
            "Краще комбінувати з органічним ростом",
            "Перевіряй якість аудиторії",
            "Використовуй обережно"
        ],

        deep: {
            features: [
                "📨 Масові інвайти",
                "🔍 Парсинг користувачів",
                "📢 Розсилки",
                "⚙️ Автоматизація залучення"
            ],

            games: [],

            extra: [
                "⚠️ Ризик бану акаунта",
                "🚫 Може порушувати ToS",
                "🤖 Часто використовує userbot"
            ],

            usage: [
                "📨 Запустити інвайти (/invite)",
                "🔍 Запустити парсинг (/parse)",
                "📢 Запустити розсилку (/broadcast)",
                "⚙️ Налаштування (/settings)"
            ]
        }
    },
    {
        name: "QuotLy",
        avatar: "assets/QuotLyBot.png",
        link: "https://t.me/QuotLyBot",

        tagline: "Перетворює повідомлення в стильні цитати",

        description: "Бот, який створює красиві зображення з повідомлень, зберігаючи стиль месенджера або застосовуючи кастомні теми.",

        flow: [
            "💬 Відповідаєш на повідомлення",
            "📥 Бот отримує текст і дані",
            "🎨 Генерує стилізоване зображення",
            "📤 Надсилає результат"
        ],

        tips: [
            "Використовуй короткі повідомлення для кращого вигляду",
            "Експериментуй зі стилями",
            "Добре підходить для мемів і цитат",
            "Emoji можуть впливати на вигляд"
        ],

        deep: {
            features: [
                "🖼 Генерація зображень з тексту",
                "🎨 Різні стилі (Telegram, iMessage)",
                "💬 Робота через відповідь на повідомлення",
                "⚙️ Кастомізація (колір, emoji)"
            ],

            games: [],

            extra: [
                "🧠 Парсинг повідомлення",
                "👤 Витяг імені та аватара",
                "⚠️ Обмеження довжини тексту"
            ],

            usage: [
                "💬 Відповісти на повідомлення",
                "🎨 Створити цитату (/q)",
                "⚙️ Налаштування стилю (/settings)",
                "🌈 Змінити кольори (/color)"
            ]
        }
    },
    {
        name: "USaver",
        avatar: "assets/UASaverBot.jpg",
        link: "https://t.me/uasaverbot",

        tagline: "Завантаження медіа з популярних платформ",

        description: "Бот, який дозволяє швидко завантажувати відео та аудіо з різних платформ, просто надіславши посилання.",

        flow: [
            "🔗 Надсилаєш посилання",
            "🤖 Бот визначає платформу",
            "⏳ Обробка",
            "📤 Отримуєш файл або варіанти"
        ],

        tips: [
            "Використовуй короткі відео для швидшого результату",
            "Не всі відео можна скачати (приватні)",
            "Якість може впливати на розмір",
            "MP3 зручно для музики"
        ],

        deep: {
            features: [
                "📥 Завантаження відео",
                "🎵 Конвертація в MP3",
                "🌍 Підтримка кількох платформ",
                "⚙️ Автовизначення URL"
            ],

            games: [],

            extra: [
                "⚠️ Ліміт Telegram (~50MB)",
                "🚫 DRM обмеження",
                "🧠 Використання downloader-інструментів"
            ],

            commands: [
                "/start",
                "/help"
            ]
        }
    },
    {
        name: "MusicSearch",
        avatar: "assets/MusicSearchBot.jpg",
        link: "https://t.me/music_search_ua_bot",

        tagline: "Пошук і відправка музики прямо в чат",

        description: "Бот для швидкого пошуку музики та отримання треків у чаті через команди або інлайн-режим.",

        flow: [
            "🔎 Вводиш назву треку",
            "📋 Отримуєш список результатів",
            "🎵 Обираєш потрібний",
            "📤 Отримуєш файл"
        ],

        tips: [
            "Пиши 'artist - track' для точності",
            "Інлайн-режим швидший у чаті",
            "Перевіряй дублікати",
            "Якість може відрізнятись"
        ],

        deep: {
            features: [
                "🔎 Пошук музики",
                "🎵 Відправка MP3",
                "⚡ Інлайн-режим",
                "📂 Робота з різними джерелами"
            ],

            games: [],

            extra: [
                "🌍 Джерела: YouTube, SoundCloud",
                "⚠️ Обмеження через авторські права",
                "🔁 Можливі дублікати"
            ],

            usage: [
                "🔎 Знайти музику (/search)",
                "🎵 Обрати трек зі списку",
                "📥 Отримати аудіо",
                "⚡ Використовувати інлайн-режим"
            ]
        }
    },
];
const defaultBotDeep = {
    "https://t.me/MafiaUaBot": {
        games: [
            {
                name: "Класична Мафія",
                description: "Соціальна гра з прихованими ролями, нічними діями та денним голосуванням."
            },
            {
                name: "Івент-сценарії",
                description: "Спеціальні режими з окремими умовами, ритмом і додатковим тиском на гравців."
            }
        ]
    }
};
const requiredBotSections = ["description", "flow", "tips"];
// Каталог ботів зараз показує лише ці deep-секції, решта редакторських полів не потрапляє в UI.
const supportedBotDeepKeys = ["games", "usage"];
let activeSection = null;
const botCatalog = bots
    .map((bot, index) => normalizeBot(bot, index))
    .filter(Boolean);
function normalizeBotDeep(deep) {
    if (!deep || typeof deep !== "object") {
        return null;
    }

    const sanitizedDeep = Object.fromEntries(
        supportedBotDeepKeys.map(key => [key, deep[key]])
    );

    const normalizedGames = Array.isArray(sanitizedDeep.games)
        ? sanitizedDeep.games
            .map(item => {
                if (!item || typeof item !== "object") {
                    return null;
                }

                const title = typeof item.title === "string"
                    ? item.title.trim()
                    : typeof item.name === "string"
                        ? item.name.trim()
                        : "";
                const description = typeof item.desc === "string"
                    ? item.desc.trim()
                    : typeof item.description === "string"
                        ? item.description.trim()
                        : "";

                if (!title || !description) {
                    return null;
                }

                return { title, description };
            })
            .filter(Boolean)
        : [];

    const normalized = {
        games: normalizedGames,
        usage: Array.isArray(sanitizedDeep.usage) ? sanitizedDeep.usage.map(item => String(item).trim()).filter(Boolean) : []
    };

    return Object.values(normalized).some(items => items.length) ? normalized : null;
}
function normalizeBot(bot, index) {
    const requiredTopLevel = ["name", "avatar", ...requiredBotSections];
    const missingTopLevel = requiredTopLevel.filter(key => !(key in bot));

    if (missingTopLevel.length) {
        console.error(`Bot at index ${index} is missing fields: ${missingTopLevel.join(", ")}`);
        return null;
    }

    const invalidListField = requiredBotSections
        .filter(key => key !== "description")
        .find(key => !Array.isArray(bot[key]) || bot[key].length === 0);

    if (typeof bot.description !== "string" || !bot.description.trim() || invalidListField) {
        console.error(`Bot "${bot.name || index}" has an invalid required structure.`);
        return null;
    }

    const botLink = typeof bot.link === "string" ? bot.link.trim() : "";
    const mergedDeep = {
        ...(defaultBotDeep[botLink] || {}),
        ...(bot.deep && typeof bot.deep === "object" ? bot.deep : {})
    };

    if (Array.isArray(bot.usage) && bot.usage.length && (!Array.isArray(mergedDeep.usage) || !mergedDeep.usage.length)) {
        mergedDeep.usage = bot.usage;
    }

    return {
        name: String(bot.name).trim(),
        avatar: String(bot.avatar).trim(),
        link: botLink,
        tagline: typeof bot.tagline === "string" ? bot.tagline.trim() : "",
        description: bot.description.trim(),
        flow: bot.flow.map(item => String(item).trim()).filter(Boolean),
        tips: bot.tips.map(item => String(item).trim()).filter(Boolean),
        deep: normalizeBotDeep(mergedDeep)
    };
}
function escapeHtml(value) {
    return String(value)
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;")
        .replaceAll('"', "&quot;")
        .replaceAll("'", "&#39;");
}
function renderBotList(items) {
    return items
        .map(item => `<li>${escapeHtml(item)}</li>`)
        .join("");
}
function renderBotUsageItem(item) {
    const value = String(item).trim();
    const dashMatch = value.match(/^(.*?)(\s-\s.+)$/);

    if (dashMatch) {
        return `
            <span class="bot-usage-label">${escapeHtml(dashMatch[1].trim())}</span>
            <span class="bot-usage-action">${escapeHtml(dashMatch[2].trim())}</span>
        `;
    }

    const commandMatch = value.match(/^(.*?)(\s\((\/[^)]+)\))$/);

    if (commandMatch) {
        return `
            <span class="bot-usage-label">${escapeHtml(commandMatch[1].trim())}</span>
            <span class="bot-usage-action">${escapeHtml(commandMatch[2].trim())}</span>
        `;
    }

    return `<span class="bot-usage-label">${escapeHtml(value)}</span>`;
}
function renderBotUsageList(items) {
    return `
        <ul class="bot-usage-list">
            ${items.map(item => `<li class="bot-usage-item">${renderBotUsageItem(item)}</li>`).join("")}
        </ul>
    `;
}
function getBotGameTarget(bot, index) {
    const gameTargets = {
        "https://t.me/MafiaUaBot": ["mafia", "events-archive"],
        "https://t.me/TruthUkrainian_Bot": ["truth-dare", "truth-fake", "who-am-i", "uno"],
        "https://t.me/OfBunkerUA_bot": ["bunker"],
        "https://t.me/codenames_ua_bot": ["codenames"],
        "https://t.me/StarsHelper1_Bot": ["blackjack", "dice"],
        "https://t.me/gavgames_bot": ["tictactoe", "memes", "minigames"]
    };

    return (gameTargets[bot?.link] || [])[index] || "";
}
function openEventsArchive() {
    const eventsTab = document.getElementById("events");

    closeBotModal();
    openTab("events");

    if (!eventsTab) {
        return;
    }

    window.setTimeout(() => {
        const top = eventsTab.getBoundingClientRect().top + window.scrollY - 92;

        window.scrollTo({
            top,
            behavior: "smooth"
        });
    }, 220);
}
function getBotDeepSections(bot) {
    if (!bot?.deep) {
        return [];
    }

    return [
        { key: "games", label: "🎮 Ігри", items: bot.deep.games },
        { key: "usage", label: "⚡ Як користуватись", items: bot.deep.usage }
    ].filter(section => Array.isArray(section.items) && section.items.length > 0);
}
function buildBotDeepActions(bot) {
    const sections = getBotDeepSections(bot);

    if (!sections.length) {
        return "";
    }

    return `
        <section class="bot-modal-section bot-modal-deep">
            <h3>⚡ ДОДАТКОВО</h3>
            <div class="bot-deep-actions" data-count="${sections.length}">
                ${sections.map(section => `
                    <button class="bot-deep-toggle" type="button" data-deep-section="${section.key}">
                        ${section.label}
                    </button>
                `).join("")}
            </div>
            <div class="bot-deep-content hidden" data-bot-deep-content></div>
        </section>
    `;
}
function renderBotDeepSection(bot, section) {
    if (!bot?.deep) {
        return "";
    }

    switch (section) {
        case "games":
            if (!bot.deep.games.length) {
                return "";
            }

            return `
                <div class="bot-game-grid">
                    ${bot.deep.games.map((game, index) => {
                        const gameTarget = getBotGameTarget(bot, index);

                        return `
                        <div class="bot-game-card${gameTarget ? " bot-game-card-link" : ""}"${gameTarget ? ` data-game="${gameTarget}"` : ""}>
                            <div class="bot-game-title">${escapeHtml(game.title)}</div>
                            <div class="bot-game-desc">${escapeHtml(game.description)}</div>
                        </div>
                    `;
                    }).join("")}
                </div>
            `;

        case "usage":
            return bot.deep.usage.length
                ? renderBotUsageList(bot.deep.usage)
                : "";

        default:
            return "";
    }
}
function toggleBotDeepSection(section) {
    const modal = document.getElementById("botModal");
    const modalBody = document.getElementById("botModalBody");
    const deepContent = modalBody?.querySelector("[data-bot-deep-content]");
    const deepButtons = modalBody?.querySelectorAll("[data-deep-section]") || [];
    const botIndex = Number(modal?.dataset.botIndex);
    const bot = Number.isInteger(botIndex) ? botCatalog[botIndex] : null;

    if (!bot || !deepContent) {
        return;
    }

    const isCollapsing = activeSection === section && !deepContent.classList.contains("hidden");

    deepButtons.forEach(button => {
        button.classList.toggle("is-active", !isCollapsing && button.dataset.deepSection === section);
    });

    if (isCollapsing) {
        deepContent.innerHTML = "";
        deepContent.classList.add("hidden");
        deepContent.classList.remove("is-visible");
        activeSection = null;
        return;
    }

    const markup = renderBotDeepSection(bot, section);

    if (!markup) {
        deepContent.innerHTML = "";
        deepContent.classList.add("hidden");
        deepContent.classList.remove("is-visible");
        activeSection = null;
        return;
    }

    deepContent.innerHTML = markup;
    deepContent.classList.remove("hidden");
    deepContent.classList.remove("is-visible");
    void deepContent.offsetWidth;
    deepContent.classList.add("is-visible");
    activeSection = section;
}
function buildBotSystems(bot) {
    if (bot.link !== "https://t.me/MafiaUaBot") {
        return "";
    }

    return `
        <section class="bot-modal-section bot-modal-systems">
            <h3>🎮 ІГРОВІ СИСТЕМИ</h3>
            <div class="bot-system-links">
                <button class="bot-system-link" type="button" data-system-target="roles">
                    <span class="bot-system-link-title">🎭 Ролі</span>
                    <span class="bot-system-link-copy">Дивись всі ролі та їх здібності</span>
                </button>
                <button class="bot-system-link" type="button" data-system-target="buffs">
                    <span class="bot-system-link-title">💥 Бафи</span>
                    <span class="bot-system-link-copy">Дивись доступні бафи та ефекти</span>
                </button>
            </div>
        </section>
    `;
}
function buildBotModal(bot) {
    const botTitle = bot.link
        ? `<a class="bot-modal-link" href="${escapeHtml(bot.link)}" target="_blank" rel="noopener noreferrer">${escapeHtml(bot.name)}</a>`
        : escapeHtml(bot.name);

    return `
        <div class="bot-modal-hero">
            <img class="bot-modal-avatar" src="${escapeHtml(bot.avatar)}" alt="${escapeHtml(bot.name)}">
            <div class="bot-modal-title-block">
                <h2 id="botModalTitle" class="bot-modal-title">${botTitle}</h2>
            </div>
        </div>

        <section class="bot-modal-section bot-modal-description">
            <h3>🧾 ОПИС</h3>
            <p>${escapeHtml(bot.description)}</p>
        </section>

        <section class="bot-modal-section">
            <h3>🎮 ЯК ПРОХОДИТЬ ГРА</h3>
            <ul class="bot-modal-list">${renderBotList(bot.flow)}</ul>
        </section>

        <section class="bot-modal-section">
            <h3>💡 ПОРАДИ</h3>
            <ul class="bot-modal-list">${renderBotList(bot.tips)}</ul>
        </section>

        ${buildBotDeepActions(bot)}
        ${buildBotSystems(bot)}
    `;
}
function renderBots() {
    const grid = document.getElementById("botsGrid");

    if (!grid) {
        return;
    }

    grid.innerHTML = botCatalog.map((bot, index) => `
        <button class="bot-card" type="button" data-bot-index="${index}" aria-label="Відкрити опис бота ${escapeHtml(bot.name)}">
            <img class="bot-card-avatar" src="${escapeHtml(bot.avatar)}" alt="${escapeHtml(bot.name)}">
            <span class="bot-card-name">${escapeHtml(bot.name)}</span>
            ${bot.tagline ? `<span class="bot-card-tagline">${escapeHtml(bot.tagline)}</span>` : ""}
        </button>
    `).join("");

    grid.querySelectorAll(".bot-card").forEach(card => {
        card.addEventListener("click", () => {
            openBotModal(Number(card.dataset.botIndex));
        });
    });
}
function openBotModal(index) {
    const bot = botCatalog[index];
    const modal = document.getElementById("botModal");
    const modalBody = document.getElementById("botModalBody");

    if (!bot || !modal || !modalBody) {
        return;
    }

    modalBody.innerHTML = buildBotModal(bot);
    modal.dataset.botIndex = String(index);
    activeSection = null;
    modal.hidden = false;
    document.body.classList.add("modal-open");
}
function closeBotModal() {
    const modal = document.getElementById("botModal");
    const modalBody = document.getElementById("botModalBody");

    if (!modal || modal.hidden) {
        return;
    }

    modal.hidden = true;
    document.body.classList.remove("modal-open");

    if (modalBody) {
        modalBody.innerHTML = "";
    }

    delete modal.dataset.botIndex;
    activeSection = null;
}
function resetBotSystems() {
    const systemsShell = document.getElementById("bot-systems");
    const groups = document.querySelectorAll(".bot-systems-group");

    showAllGames();
    document.querySelectorAll("#bot-systems-roles .weekday").forEach(section => {
        section.classList.remove("active");
    });

    if (systemsShell) {
        systemsShell.hidden = true;
    }

    groups.forEach(group => {
        group.hidden = true;
        group.classList.remove("is-revealed");
    });
}
function expandRoleSystems() {
    document.querySelectorAll("#bot-systems-roles .weekday")
        .forEach(section => {
            section.classList.add("active");
        });
}
function scrollToBotSystem(system, game) {
    if (system === "games" && game === "events-archive") {
        openEventsArchive();
        return;
    }

    const targetMap = {
        roles: "bot-systems-roles",
        buffs: "bot-systems-buffs",
        games: "bot-systems-games"
    };
    const targetId = targetMap[system] || targetMap.roles;
    const rolesTab = document.getElementById("roles");
    const systemsShell = document.getElementById("bot-systems");
    const targetGroup = document.getElementById(targetId);

    closeBotModal();

    const scrollToTarget = () => {
        if (!systemsShell || !targetGroup) {
            return;
        }

        systemsShell.hidden = false;
        targetGroup.hidden = false;
        targetGroup.classList.remove("is-revealed");
        void targetGroup.offsetWidth;
        targetGroup.classList.add("is-revealed");

        if (system === "roles") {
            expandRoleSystems();
        }

        if (system === "games") {
            if (game && showOnlyGame(game)) {
                return;
            }

            showAllGames();
        }

        const target = targetGroup;
        const top = target.getBoundingClientRect().top + window.scrollY - 92;

        window.scrollTo({
            top,
            behavior: "smooth"
        });
    };

    //if (!rolesTab || !rolesTab.classList.contains("active")) {
    //    openTab("roles");
    //    window.setTimeout(scrollToTarget, 220);
    //    return;
    //}

    //if (systemsShell.hidden) {
    //    window.setTimeout(scrollToTarget, 60);
    //    return;
    //}

    scrollToTarget();
}
function setupBotModal() {
    const modal = document.getElementById("botModal");

    if (!modal || modal.dataset.ready === "true") {
        return;
    }

    modal.addEventListener("click", event => {
        if (event.target.closest("[data-close-modal]") || event.target.closest(".bot-modal-close")) {
            closeBotModal();
            return;
        }

        const gameCard = event.target.closest(".bot-game-card[data-game]");

        if (gameCard) {
            scrollToBotSystem("games", gameCard.dataset.game);
            return;
        }

        const deepButton = event.target.closest("[data-deep-section]");

        if (deepButton) {
            toggleBotDeepSection(deepButton.dataset.deepSection);
            return;
        }

        const systemButton = event.target.closest("[data-system-target]");

        if (systemButton) {
            scrollToBotSystem(systemButton.dataset.systemTarget);
        }
    });

    modal.dataset.ready = "true";
}
